app/controllers/routes/views.py
import os

from datetime import datetime
from passlib.hash import pbkdf2_sha256
from werkzeug.utils import secure_filename

from flask import (
    render_template,
    request,
    Blueprint,
    url_for,
    redirect,
    current_app,
    send_from_directory,
    abort,
    flash,
)
from flask_login import (
    login_required,
    login_user,
    logout_user,
    current_user,
    confirm_login,
)
from flask_limiter import Limiter
from flask_limiter.util import get_remote_address

from app.controllers.forms.forms import *
from app.controllers.forms.options import opcoes_falha
from app.controllers.functions.email import enviar_email_dm, enviar_email_generico
from app.controllers.functions.helpers import *
from app.controllers.constants import *
from app.controllers.functions.dictionaries import *

limiter = Limiter(
    get_remote_address,
    app=current_app,
)
views = Blueprint(
    "views", __name__, static_folder="static", template_folder="templates"
)


@views.route("/", methods=["GET", "POST"])
def index():
    """
    Renderiza a página inicial do projeto
    """

    form_login = LoginForm(request.form)
    return render_template(
        "views/index.html",
        title="Página inicial",
        secomp_now=secomp_now[0],
        secomp=secomp[0],
        secomp_email=secomp_email,
        secompEdition=secomp_edition,
        form_login=form_login,
    )


@views.route("/contato", methods=["POST", "GET"])
def contato_dm():
    """
    Página de contato
    """
    form = ContatoForm(request.form)
    form_login = LoginForm(request.form)
    if form.validate_on_submit():
        nome = form.nome_completo.data
        email = form.email.data
        mensagem = form.mensagem.data
        enviar_email_dm(nome, email, mensagem)
        return render_template(
            "views/contato.html", form=form, enviado=True, form_login=form_login
        )
    return render_template("views/contato.html", form=form, form_login=form_login)


@views.route("/bug-report", methods=["POST", "GET"])
def bug_report():
    """
    Página de envio do bug report
    """
    form_login = LoginForm(request.form)
    form = BugReportForm()

    if form.validate_on_submit():
        info = {
            "assunto": "SECOMP - Bug Report",  # assunto do email
            "email": "ti@secompufscar.com.br",  # email destino
            "nome": form.autor.data,  # nome do autor
            "titulo": form.titulo.data,
            "descricao": form.descricao.data,
            "impacto": form.impacto.data,
            "template": "email/report.html",  # path do template (raiz dentro do diretório 'templates')
            "footer": "TI X SECOMP UFSCar",
        }

        if form.falha.data == 8:
            info["falha"] = form.outra_falha.data
        else:
            info["falha"] = opcoes_falha[form.falha.data][1]

        if form.contato.data:
            info["contato"] = form.contato.data

        anexos = []
        if form.anexo.data:
            blobs = request.files.getlist("anexo")
            for blob in blobs:
                filename = secure_filename(blob.filename)
                filename = f'{info["titulo"]}_{filename}'
                upload_path = os.path.join(
                    current_app.config["UPLOAD_FOLDER"], "reports"
                )
                if not os.path.exists(upload_path):
                    os.makedirs(upload_path)
                abs_path = os.path.join(upload_path, filename)
                anexos.append(abs_path)
                blob.save(abs_path)

        enviar_email_generico(info=info, anexo=anexos)
        flash("Seu report foi enviado!")
        return render_template(
            "views/bug_report.html", form=form, form_login=form_login
        )
    return render_template("views/bug_report.html", form=form, form_login=form_login)


@views.route("/constr", methods=["GET", "POST"])
def constr():
    form_login = LoginForm(request.form)
    return render_template(
        "views/em_constr.html", title="Página em construção", form_login=form_login
    )


@views.route("/sobre", methods=["GET", "POST"])
def sobre():
    form_login = LoginForm(request.form)
    return render_template(
        "views/sobre.html", title="Sobre a Secomp", form_login=form_login
    )


@views.route("/descontos", methods=["GET", "POST"])
def descontos():
    form_login = LoginForm(request.form)
    return render_template(
        "views/descontos.html", title="Descontos", form_login=form_login
    )


@views.route("/cronograma", methods=["GET", "POST"])
def cronograma():
    form_login = LoginForm(request.form)
    return render_template(
        "views/cronograma.html",
        title="Cronograma",
        form_login=form_login,
        info_cronograma=get_cronograma(),
    )


@views.route("/equipe", methods=["GET", "POST"])
def equipe():
    form_login = LoginForm(request.form)
    return render_template(
        "views/equipe.html",
        title="Equipe",
        form_login=form_login,
        info_equipe=get_equipe(database=True),
    )


@views.route("/faq", methods=["GET", "POST"])
def faq():
    form_login = LoginForm(request.form)
    return render_template("views/faq.html", title="FAQ", form_login=form_login)


@views.route("/ctf", methods=["GET", "POST"])
def ctf():
    form_login = LoginForm(request.form)
    return render_template("views/ctf.html", title="CTF", form_login=form_login)


@views.route("/gamejam", methods=["GET", "POST"])
def gamejam():
    form_login = LoginForm(request.form)
    return render_template("views/gamejam.html", title="CTF", form_login=form_login)


@views.route("/desafio", methods=["GET", "POST"])
def desafio():
    form_login = LoginForm(request.form)
    return render_template("views/desafio.html", title="CTF", form_login=form_login)


@limiter.limit("50/day")
@views.route("/login", methods=["GET", "POST"])
def login():
    form = LoginForm(request.form)

    if form.validate_on_submit():
        user = db.session.query(Usuario).filter_by(email=form.email.data).first()
        if user:
            (
                atividade_confirmada,
                atividade,
                view_atividade,
            ) = confirmacao_atividade_ministrante(user)
            if user.senha is not None and pbkdf2_sha256.verify(
                form.senha.data, user.senha
            ):
                user.autenticado = True
                user.ultimo_login = datetime.now()
                db.session.add(user)
                db.session.commit()
                login_user(user, remember=True)
                if atividade_confirmada == False:
                    return redirect(url_for("conteudo.dados_hospedagem_transporte"))
                return redirect(url_for("participantes.dashboard"))
        return render_template(
            "views/login.html", form_login=form, form=form, erro=True
        )
    return render_template("views/login.html", form_login=form, form=form)


@limiter.limit("50/day")
@views.route("/confirm-login", methods=["GET", "POST"])
def relogin():
    form = LoginForm(request.form)
    if form.validate_on_submit():
        user = db.session.query(Usuario).filter_by(email=form.email.data).first()
        if user:
            if user.senha is not None and pbkdf2_sha256.verify(
                form.senha.data, user.senha
            ):
                user.autenticado = True
                user.ultimo_login = datetime.now()
                db.session.add(user)
                db.session.commit()
                confirm_login()
                return redirect(url_for("participantes.dashboard"))
        return render_template(
            "views/login.html", form_login=form, form=form, erro=True
        )
    return render_template("views/login.html", form_login=form, form=form)


@views.route("/logout", methods=["GET"])
@login_required
def logout():
    """
    Renderiza a página de logout do projeto
    """
    user = current_user
    user.autenticado = False
    db.session.add(user)
    db.session.commit()
    logout_user()
    return redirect(url_for("views.login"))


@views.route("/senhas", methods=["GET"])
def senhas():
    return render_template("views/requisito_50.html")


@views.route("/patrocinadores", methods=["GET"])
def patrocinadores():
    """
    Renderiza página referente aos patrocinadores da edição atual
    """

    form = LoginForm(request.form)
    patrocinadores = (
        db.session.query(Patrocinador)
        .filter_by(ativo_site=True)
        .order_by(Patrocinador.id_cota)
    )
    return render_template(
        "views/patrocinadores.html",
        patrocinadores=patrocinadores,
        form_login=form,
        edicao=EDICAO_ATUAL,
    )


@views.route("/pontuacao", methods=["GET"])
def pontuacao_compcases():
    """
    Renderiza página referente a pontuação geral do COMPCases
    """
    """
    form = LoginForm(request.form)
    participantes = get_ranking_pontuacao()
    participante_logado = None
    try:
        participante_logado = db.session.query(Participante).filter_by(
            usuario=current_user).first()
    except:
        pass
    return render_template('views/pontuacao_compcases.html', participantes=participantes, ult_day = False, participante_logado=participante_logado, form_login=form)
    """
    return redirect(url_for(".index"))


@views.route("/pontuacao-diaria", methods=["GET"])
def pontuacao_compcases_day():
    """
    Renderiza página referente a pontuação do dia atual do COMPCases
    """
    form = LoginForm(request.form)
    participantes = []
    aux = get_ranking_pontuacao_by_day()
    # for x in aux:
    #   participantes.append(db.session.query(Participante).filter_by(id=x.id).first())
    """
    Gambiarra de última hora: bubble sort para ordenar os participantes por pontuação
    """
    """for i in range(len(participantes)):
        for j in range(len(participantes)):
            if (participantes[i].pontuacao > participantes[j].pontuacao):
                aux = participantes[i]

app/templates/views/contato.html
{% extends "base.html" %}
{% import "wtf.html" as wtf %}

{% block content %}
<div class="container">
  <div class="row justify-content-center pt-4">

    <div class="col-md-12 text-center">
      <h2>Contato</h2>
      {% if enviado %}
      <h5>Enviado</h5>
      {% endif %}
    </div>

    <div class="row justify-content-around pt-3">
      <div class="col-md-5 text-center">
        <h1 class="display-4"><i class="fas fa-2x fa-comments"></i></h1>
        <p class="text-justify"> Tem alguma dúvida, sugestão, elogio, crítica?
          Ou quer apenas deixar um recado para a SECOMP?
          Entre em contato com a organização preenchendo o campo ao lado!
        </p>
      </div>
      <div class="col-md-5">
        <form method="POST" action="/contato">
          {{ form.hidden_tag() }}
          {{ wtf.form_field(form.nome_completo) }}
          {{ wtf.form_field(form.email) }}
          {{ wtf.form_field(form.mensagem) }}
          {{ wtf.form_field(form.recaptcha) }}
          <div class="text-center">
            <button type="submit" class="btn btn-primary btn-block mt-5">Enviar</button>
          </div>
        </form>
      </div>
    </div>

    <div class="row justify-content-center pt-3">
      <div class="col-sm-3 align-self-center">
        <img class="img-fluid" src="{{url_for('static', filename='images/logo-secomp.png')}}">
      </div>
      <div class="col-sm-3 align-self-center">
        <img class="img-fluid" src="{{url_for('static', filename='images/logo-dc.png')}}">
      </div>
      <div class="col-sm-3 align-self-center">
        <img class="img-fluid" src="{{url_for('static', filename='images/logo-ufscar.png')}}">
      </div>
    </div>
  </div>
</div>
{% endblock %}

app/templates/views/descontos.html
{% extends "base.html" %}

{% block content %}

<div class="container pt-4">
  <div class="col-md-12 text-center">
    <h2>Descontos para participantes da X SECOMP</h2>
  </div>
</div>

<div class="container pt-3 pb-3">

  <div class="row text-center justify-content-center align-items-center mt-4">
    <div class="col-md-2 text-center">
      <img class="img-fluid mb-2" src="https://secompufscar.com.br/uploads/logo_patrocinadores/yo_colorida.png">
    </div>
    <div class="col-md-8">
      <h3 class="pt-2 pb-2">Yo Konno Temakeria</h3>
      <h5>Consumo acima de 30,00 ganha uma sobremesa ou hossomakis de salmão</h5>
      <h6>(com apresentação do crachá)</h6>
    </div>
  </div>

  <div class="row text-center justify-content-center align-items-center mt-4">
    <div class="col-md-2 text-center">
      <img class="img-fluid mb-2" src="https://secompufscar.com.br/uploads/logo_patrocinadores/japa_colorida.png">
    </div>
    <div class="col-md-8">
      <h3 class="pt-2 pb-2">Japa Açaí</h3>
      <h5>10% de desconto para os participantes nos dias do evento</h5>
      <h6>(com apresentação do crachá)</h6>
    </div>
  </div>

  <div class="row text-center justify-content-center align-items-center mt-4">
    <div class="col-md-2 text-center">
      <img class="img-fluid mb-2" src="https://secompufscar.com.br/uploads/logo_patrocinadores/dogrego_colorida.png">
    </div>
    <div class="col-md-8">
      <h3 class="pt-2 pb-2">DoGrego Foodtruck</h3>
      <h5>10% nos produtos para os participantes nos dias do evento</h5>
      <h6>(com apresentação do crachá)</h6>
    </div>
  </div>

  <div class="row text-center justify-content-center align-items-center mt-4">
    <div class="col-md-2 text-center">
      <img class="img-fluid mb-2" src="{{ url_for('static', filename='images/patrocinadores/jamaica_colorida.png') }}">
    </div>
    <div class="col-md-8">
      <h3 class="pt-2 pb-2">Jamaica Foodtruck</h3>
      <h5>X SECOMP em 3 tipos de hambúrgueres artesanais (carne, frango e vegano)</h5>
      <h6>Preço padrão: R$ 24,90</h6>
      <h6>Apresentando Cracha do kit: 15,00 sem batata ou 19,90 com uma porção pequena de batata </h6>
    </div>
  </div>

  <div class="row text-center justify-content-center align-items-center mt-4">
    <div class="col-md-2 text-center">
      <img class="img-fluid mb-2" src="https://secompufscar.com.br/static/images/testeseuburguer.png">
    </div>
    <div class="col-md-8">
      <h3 class="pt-2 pb-2">Seu burguer</h3>
      <h5>5% de desconto para os participantes nos dias do evento</h5>
      <h6>(com apresentação do crachá)</h6>
    </div>
  </div>

  <div class="row text-center justify-content-center align-items-center mt-4">
    <div class="col-md-2 text-center">
      <img class="img-fluid mb-2" src="{{ url_for('static', filename='images/patrocinadores/subway_colorida.png') }}">
    </div>
    <div class="col-md-8">
      <h3 class="pt-2 pb-2">Subway</h3>
      <h4>Subway em dobro</h4>
      <h5>Válido para as unidades: Avenida São Carlos, Shopping Iguatemi e Havan</h5>
      <h6>(com apresentação do crachá)</h6>
    </div>
  </div>

  <div class="row text-center justify-content-center align-items-center mt-4">
    <div class="col-md-2 text-center">
      <img class="img-fluid mb-2" src="{{ url_for('static', filename='images/patrocinadores/nerd_colorida.png') }}">
    </div>
    <div class="col-md-8">
      <h3 class="pt-2 pb-2">Nerd Stickers</h3>
      <h5>Cupom de 10% de desconto para os participantes: Secomp10%</h5>
      <h6><a href="https://www.nerdstickers.com.br/" style="text-decoration: none;" target="_blank">Acesse o site</a></h6>
    </div>
  </div>

  <div class="row text-center justify-content-center align-items-center mt-4">
    <div class="col-md-2 text-center">
      <img class="img-fluid mb-2"
        src="https://secompufscar.com.br/uploads/logo_patrocinadores/macarronato_colorida.png">
    </div>
    <div class="col-md-8">
      <h3 class="pt-2 pb-2">Macarronato</h3>
      <h5>Cupom de 10% de desconto para os participantes.</h5>
      <h6>(com apresentação do crachá)</h6>
      <h6>Sorteio: Cinco pratos de macarrão na chapa, cada um com quatro opcionais, e uma coca-cola lata.</h6>
    </div>
  </div>

  <div class="row text-center justify-content-center align-items-center mt-4">
    <div class="col-md-2 text-center">
      <img class="img-fluid mb-2"
        src="https://secompufscar.com.br/uploads/logo_patrocinadores/rockburger_colorida.png">
    </div>
    <div class="col-md-8">
      <h3 class="pt-2 pb-2">Rock Burger</h3>
      <h5>10% de desconto na compra de burger + bebida</h5>
      <h6>(com apresentação do crachá e um documento com foto)</h6>
    </div>
  </div>

  <div class="row text-center justify-content-center align-items-center mt-4">
    <div class="col-md-2 text-center">
      <img class="img-fluid mb-2"
        src="https://scontent-gru2-1.xx.fbcdn.net/v/t1.0-9/48420527_316167365665638_5593552006565330944_n.jpg?_nc_cat=102&_nc_oc=AQnhRtccsZYTyUoTxtaXeYeBsGpquYF20rU_EGsp0yteMeSRyjZJIROqEWuf-7rg2tA&_nc_ht=scontent-gru2-1.xx&oh=38b7072a728ba9bbaa90cbbc7c4147e2&oe=5DF05B00">
    </div>
    <div class="col-md-8">
      <h3 class="pt-2 pb-2">Billy's BBQ</h3>
      <h5>10% de desconto (exceto promoções)</h5>
      <h6>(com apresentação do crachá)</h6>
    </div>
  </div>

  <div class="row text-center justify-content-center align-items-center mt-4">
    <div class="col-md-2 text-center">
      <img class="img-fluid mb-2"
        src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSFwGtcjdoeXgdGB0nI03z9PonOd3NYC1EgTqCJZ-gY0BSMTrV4">
    </div>
    <div class="col-md-8">
      <h3 class="pt-2 pb-2">Estação da luz</h3>
      <h5>8% de desconto</h5>
      <h6>(com apresentação do crachá)</h6>
    </div>
  </div>

  <div class="row text-center justify-content-center align-items-center mt-4">
    <div class="col-md-2 text-center">
      <img class="img-fluid mb-2"
        src="https://secompufscar.com.br/static/images/logo-colorida.png">
    </div>
    <div class="col-md-8">
      <h3 class="pt-2 pb-2">Restaurante São Carlos</h3>
      <h5>10% de desconto</h5>
      <h6>(com apresentação do crachá)</h6>
    </div>
  </div>

  <div class="row text-center justify-content-center align-items-center mt-4">
    <div class="col-md-2 text-center">
      <img class="img-fluid mb-2"
        src="https://secompufscar.com.br/static/images/logo-colorida.png">
    </div>
    <div class="col-md-8">
      <h3 class="pt-2 pb-2">Seo Gera</h3>
      <h5>10% de desconto (exceto promoções)</h5>
      <h6>(com apresentação do crachá)</h6>
    </div>
  </div>

  <div class="row text-center justify-content-center align-items-center mt-4">
    <div class="col-md-2 text-center">
      <img class="img-fluid mb-2"
        src="https://secompufscar.com.br/static/images/logo-colorida.png">
    </div>
    <div class="col-md-8">
      <h3 class="pt-2 pb-2">Trem Bão</h3>
      <h5>20% de desconto</h5>
      <h6>(com apresentação do crachá)</h6>
    </div>
  </div>

  <div class="row text-center justify-content-center align-items-center mt-4">
    <div class="col-md-2 text-center">
      <img class="img-fluid mb-2"
        src="https://secompufscar.com.br/static/images/logo-colorida.png">
    </div>
    <div class="col-md-8">
      <h3 class="pt-2 pb-2">Vai Uai</h3>
      <h5>Desconto no Self service</h5>
      <h6>Terça à sexta: de R$25,90 por R$23,90
      <br>Sábado e domingo: de R$35,90 por R$31,90</h6>
      <h6>(com apresentação do crachá)</h6>
    </div>
  </div>

</div>


<div class="container">
  <div class="row justify-content-center p-3">
    <div class="col-md-12 text-center">
      <h4>Realização</h4>
    </div>
    <div class="col-sm-3 align-self-center">
      <img class="img-fluid" src="{{url_for('static', filename='images/logo-secomp.png')}}">
    </div>
    <div class="col-sm-3 align-self-center">
      <img class="img-fluid" src="{{url_for('static', filename='images/logo-dc.png')}}">
    </div>
    <div class="col-sm-3 align-self-center">
      <img class="img-fluid" src="{{url_for('static', filename='images/logo-ufscar.png')}}">
    </div>
  </div>
</div>


{% endblock %}

app/templates/views/equipe.html
{% extends "base.html" %}


{% block content %}

<link href="{{ url_for('static', filename='css/equipe.css') }}" rel="stylesheet" type="text/css" />

<div class="container">
    {% for diretoria in info_equipe %}
        <h2 class="section-title text-center pt-1">{{ diretoria }}</h2>
        <div class="row justify-content-center pb-3">
            {% for membro in info_equipe[diretoria] %}
                <div class="pb-3 pl-2 pr-2">
                    <div class="card text-center" style="width: 18rem; height: 17rem;">
                        {% if info_equipe[diretoria][membro]['bio'] is not sameas None and 
                              info_equipe[diretoria][membro]['bio'] is not sameas "" %}
                            <i class="fas fa-info-circle fa-lg card-info"></i>
                            <div class="card-body card-dual">
                        {% else %}
                            <div class="card-body">
                        {% endif %}
                            <img class="rounded-circle img-equipe mb-3"
                                src="{{ url_for('static', filename='images/equipe/%s' % info_equipe[diretoria][membro]['img']) }}"
                                alt="Foto de {{ membro }}">

                            <h5 class="card-title">{{ membro }}</h5>

                            <p class="desc-membro">{{ info_equipe[diretoria][membro]['bio'] }}</p>

                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    {% endfor %}
</div>

{% endblock %}

app/templates/views/index.html
{% extends "base.html" %}

{% block styles %}

{{ super() }}
<link href="{{ url_for('static', filename='css/index.css') }}" rel="stylesheet" type="text/css" />
<link href="{{ url_for('static', filename='swiper/swiper.min.css') }}" rel="stylesheet" type="text/css" />

<style>
	#car1 {
		background-image: url("{{ url_for('static', filename='images/bg.jpeg') }}");
	}
</style>
{% endblock %}


{% block content %}
<img id="car1" class="background">
<div class="swiper-container">
	<div class="swiper-wrapper">

		<div class="swiper-slide">
			<div class="col-md-12">
				<div class="row align-items-center justify-content-center text-center text-white bg-fade pb-2 m-1">
					<div class="col-md-12 mb-1">
						<img class="logoL" src="{{ url_for('static', filename='images/logo-branca.png') }}">
						<img class="logoP" src="{{ url_for('static', filename='images/logo-colorida.png') }}">
					</div>
					<div class="col-md-12 pb-5 pt-2">
						<h4 id="texto1">Para saber o que vai rolar na SECOMP
						<br>acesse nosso
						<a href="{{ url_for('views.cronograma') }}"><b>cronograma</b></a></h4>
					</div>
				</div>
			</div>
		</div>

		<div class="swiper-slide">

			<div class="container text-center">
				<div class="row justify-content-center align-items-center text-white bg-fade m-1">
					<div class="col-md-12">
						<h1 class="mt-5 mb-5">Baixe nosso aplicativo!</h1>

						<a href="https://play.google.com/store/apps/details?id=br.com.secompufscar.app" target="_blank"
							style="font-size: 4vh; padding: 2vh; text-decoration: none; background-color: #008cb5ee; color: #fff; border-radius: 1rem;">
							Playstore</a>
						<h5 class="mt-5 mb-5">Disponível apenas para Android</h5>
					</div>
				</div>
			</div>
		</div>

		<div class="swiper-slide">

			<div class="container-fluid text-center">
				<div class="row justify-content-center align-items-center text-white bg-fade m-1">
					<div class="col-md-12">
						<h1 style="padding-top: 6vh; padding-bottom: 9vh; font-size: 6vh;">Quer participar?</h1>
						<a href="{{ url_for('participantes.cadastro') }}"
							style="font-size: 4vh; padding: 2vh; text-decoration: none; background-color: #008cb5ee; color: #fff; border-radius: 1rem;">
							Faça seu cadastro!</a>
						<h5 style="padding-top: 5vh; padding-bottom: 3vh;">Infelizmente, as inscrições estão encerradas.
							<br>Porém, é possível realizar o cadastro no site e inscrever-se presencialmente, durante o
							credenciamento do evento
							(:</h5>
						<h5 style="padding-top: 3vh; padding-bottom: 3vh;">O evento é gratuito e aberto para toda a
							comunidade!</h5>
					</div>
				</div>
			</div>
		</div>

		<div class="swiper-slide">

			<div class="container text-center">
				<div class="row justify-content-center align-items-center text-white bg-fade m-1">
					<div class="col-md-12">
						<h1 class="mt-5 mb-5">Conheça nossas parcerias!</h1>

						<a href="{{ url_for('views.patrocinadores') }}"
							style="font-size: 4vh; padding: 2vh; text-decoration: none; background-color: #008cb5ee; color: #fff; border-radius: 1rem;">
							Patrocinadores</a>

						<h5 class="mt-5 mb-5">Sem elas, nosso evento não seria o mesmo.</h5>
					</div>
				</div>
			</div>
		</div>

		<div class="swiper-slide">

			<div class="container text-center">
				<div class="row justify-content-center align-items-center text-white bg-fade m-1">
					<div class="col-md-12">
						<h1 class="mt-5">Confira a pontuação</h1>
						<h3 class="mb-5">dos 10 primeiros colocados</h3>

						<a href="{{ url_for('views.pontuacao_compcases') }}"
							style="font-size: 4vh; padding: 2vh; text-decoration: none; background-color: #008cb5ee; color: #fff; border-radius: 1rem;">
							COMPCases</a>
						<h5 class="mt-5 mb-5">Para verificar sua pontuação, basta fazer login e acessar a mesma página!
						</h5>
					</div>
				</div>
			</div>
		</div>

	</div>
	<div class="swiper-pagination"></div>
</div>

{% endblock %}

{% block footer %}{% endblock %}

{% block scripts %}

{{ super() }}

<script src="{{ url_for('static', filename='swiper/swiper.min.js') }}"></script>

<script>

	var body = document.body;
	var slider = new Swiper('.swiper-container', {
		pagination: '.swiper-pagination',
		direction: 'horizontal',
		loop: true,
		slidesPerView: 1,
		paginationClickable: true,
		mousewheelControl: true,
		onSlideChangeStart: function (swiper) {
			var currentSlide = swiper.slides[swiper.activeIndex];
		},
	});

</script>
{% endblock %}

app/templates/views/pontuacao_compcases.html
{% extends "base.html" %}

{% block content %}

<style>
    tr {
        color: var(--font-color);
    }
</style>

<div class="container">
    <div class="row justify-content-center text-center pt-4 pb-4">
        <div class="col-md-12 pb-4">
            {% if not ult_day %}
                <h2>Pontuação COMPCases</h2>
                <br>
                <a href="{{ url_for('views.pontuacao_compcases_day') }}"><h4>Clique aqui para ver a pontuação diária!</h4>
                </a><h6>Confira o <a href="{{ url_for('static', filename='juridic/compcases.pdf') }}"
                                target="_blank">
                                edital</a>
            {% else %}
                <h2>Pontuação diária - COMPCases</h2>
            {% endif %}
        </div>
        {% if participante_logado != None and ult_day == False%}
        <div class="col-md-12 pb-4">
            <h4><b>{{ participante_logado.usuario.primeiro_nome }} {{ participante_logado.usuario.sobrenome }}:</b> {{ participante_logado.pontuacao }} pontos</h4>
        </div>
        {% endif %}
        <table class="table table-striped table-bordered">
            <thead>
                <tr>
                    <th>Posição</th>
                    <th>Nome</th>
                    <th>Pontuação</th>
                </tr>
            </thead>
            <tbody>
                {% for participante in participantes %}
                    {% if participante.pontuacao != 0 %}
                        <tr>
                            {% if ult_day %}
                                <td>{{ loop.index }}</td>
                                <td>{{ participante.primeiro_nome }} {{ participante.sobrenome }}</td>
                                <td>{{ participante.pont }}</td>
                            {% else %}
                                <td>{{ loop.index }}</td>
                                <td>{{ participante.usuario.primeiro_nome }} {{ participante.usuario.sobrenome }}</td>
                                <td>{{ participante.pontuacao }}</td>
                            {% endif %}
                        </tr>
                    {% endif %}
                {% endfor %}
            </tbody>
        </table>

    </div>
</div>

{% endblock %}

app/templates/views/requisito_50.html
<h1>
    -- ....- ....- ----. ----. ----. ....- ----- ..--- ....- .---- ----. -....- .... ...-- ..... ----. ----. ..--- ....- ....- ..--- -.... ----- --...
</h1>
<audio controls autoplay>
    <source src="{{ url_for('static', filename='images/requisito.mp3')}}" type="audio/mp3">
</audio>