app/controllers/routes/gerenciar.py
import uuid

from flask import render_template, request, redirect, abort, url_for, Blueprint
from flask_login import login_required, current_user
from random import SystemRandom
from secrets import token_urlsafe

from app.models.models import *
from app.controllers.forms.forms import *
from app.controllers.forms.options import *
from app.controllers.functions.dictionaries import *
from app.controllers.functions.helpers import *
from app.controllers.functions.email import *
from app.controllers.forms.validators import *

gerenciar = Blueprint("gerenciar", __name__, static_folder="static", template_folder="templates", url_prefix="/gerenciar")


@gerenciar.route("/")
@login_required
def index():
    if possui_permissao(current_user) or current_user.is_admin():
        form_login = LoginForm(request.form)
        permissoes = db.session.query(Permissao).all()
        permissoes = {x.nome: x for x in permissoes}
        return render_template("gerenciar/gerenciar.html", usuario=current_user, permissoes=permissoes, form_login=form_login)
    else:
        abort(403)


@gerenciar.route("/estoque-camisetas")
@login_required
def estoque_camisetas():
    permissoes = current_user.getPermissoes()
    if "ALTERAR_CAMISETAS" in permissoes or current_user.is_admin():
        participante = db.session.query(Participante).filter_by(usuario=current_user, id_evento=get_id_evento_atual()).first()
        form_login = LoginForm(request.form)
        camisetas = db.session.query(Camiseta)
        return render_template(
            "gerenciar/controle_camisetas.html",
            camisetas=camisetas,
            usuario=current_user,
            participante=participante,
            form_login=form_login,
        )
    else:
        abort(403)


@gerenciar.route("/estoque-camisetas/<tamanho>")
@login_required
def estoque_camisetas_por_tamanho(tamanho):
    permissoes = current_user.getPermissoes()
    if "ALTERAR_CAMISETAS" in permissoes or current_user.is_admin():
        participante = db.session.query(Participante).filter_by(usuario=current_user, id_evento=get_id_evento_atual()).first()
        form_login = LoginForm(request.form)
        camisetas = db.session.query(Camiseta).filter_by(tamanho=tamanho)
        return render_template(
            "gerenciar/controle_camisetas.html",
            camisetas=camisetas,
            usuario=current_user,
            participante=participante,
            form_login=form_login,
        )
    else:
        abort(403)


@gerenciar.route("/cadastro-patrocinador", methods=["POST", "GET"])
@login_required
def cadastro_patrocinador():
    permissoes = current_user.getPermissoes()
    if "CADASTRAR_PATROCINADOR" in permissoes or current_user.is_admin():
        participante = db.session.query(Participante).filter_by(usuario=current_user, id_evento=get_id_evento_atual()).first()
        form_login = LoginForm(request.form)
        form = PatrocinadorForm(request.form)
        if form.validate_on_submit():
            patrocinador = Patrocinador(
                nome_empresa=form.nome_empresa.data,
                logo=form.logo.data,
                ativo_site=form.ativo_site.data,
                id_cota=form.id_cota.data,
                link_website=form.link_website.data,
                form_login=form_login,
            )
            db.session.add(patrocinador)
            db.session.flush()
            db.session.commit()
            return redirect(url_for(".cadastro-patrocinador"))
        else:
            return render_template(
                "gerenciar/cadastro_patrocinador.html",
                usuario=current_user,
                participante=participante,
                form=form,
                form_login=form_login,
            )
    else:
        abort(403)


@gerenciar.route("/venda-kits", methods=["POST", "GET"])
@login_required
def vender_kits():
    permissoes = current_user.getPermissoes()
    meu_participante = db.session.query(Participante).filter_by(usuario=current_user, id_evento=get_id_evento_atual()).first()
    if "VENDA_PRESENCIAL" in permissoes or current_user.is_admin():
        form_login = LoginForm(request.form)
        form = VendaKitForm(request.form)
        form.participante.choices = get_participantes()
        form.camiseta.choices = get_opcoes_camisetas()
        if form.validate_on_submit() and form.participante.data is not None:
            camiseta = db.session.query(Camiseta).filter_by(id=form.camiseta.data).first()
            participante = db.session.query(Participante).filter_by(id=form.participante.data).first()
            if camiseta.quantidade_restante > 0:
                valor = form.valor.data
                pagamento = Pagamento(
                    id_participante=participante.id, descricao="Kit", valor=valor, efetuado=True, metodo_pagamento="Presencial"
                )
                pagamento.id_camiseta = form.camiseta.data
                participante.pagamentos.append(pagamento)
                if camiseta.quantidade_restante > 0:
                    camiseta.quantidade_restante = camiseta.quantidade_restante - 1
                participante.opcao_coffee = form.restricao_coffee.data
                alerta = (
                    "Compra de "
                    + participante.usuario.primeiro_nome
                    + " "
                    + participante.usuario.sobrenome
                    + " realizada com sucesso! R$ "
                    + str(valor)
                    + ". Camiseta: "
                    + camiseta.tamanho
                    + " e restrição alimentar: "
                    + get_nome_restricao(participante.opcao_coffee)
                )
                db.session.add(camiseta)
                db.session.add(participante)
                db.session.commit()
                return render_template(
                    "gerenciar/venda_de_kits.html",
                    alerta=alerta,
                    form=form,
                    form_login=form_login,
                    usuario=current_user,
                    participante=meu_participante,
                )
            elif camiseta.quantidade_restante == 0:
                return render_template(
                    "gerenciar/venda_de_kits.html",
                    alerta="Sem estoque para " + camiseta.tamanho,
                    form=form,
                    form_login=form_login,
                    usuario=current_user,
                    participante=meu_participante,
                )
        return render_template(
            "gerenciar/venda_de_kits.html",
            alerta="Preencha o formulário abaixo",
            form=form,
            form_login=form_login,
            usuario=current_user,
            participante=meu_participante,
        )
    else:
        abort(403)


@gerenciar.route("/sorteio")
@login_required
def sorteia_usuario():
    permissoes = current_user.getPermissoes()
    if "SORTEAR" in permissoes or current_user.is_admin():
        participante = db.session.query(Participante).filter_by(usuario=current_user, id_evento=get_id_evento_atual()).first()
        form_login = LoginForm(request.form)
        form = SorteioForm(request.form)
        return render_template(
            "gerenciar/sortear_usuario.html",
            form=form,
            usuario=current_user,
            participante=participante,
            sorteando=False,
            form_login=form_login,
        )
    else:
        abort(403)


@gerenciar.route("/sorteio/sortear", methods=["POST"])
@login_required
def sortear():
    permissoes = current_user.getPermissoes()
    if "SORTEAR" in permissoes or current_user.is_admin():
        form_login = LoginForm(request.form)
        form = SorteioForm(request.form)
        presencas = db.session.query(Atividade).filter_by(id=int(form.atividades.data)).first().presencas
        if len(presencas) > 0:
            participante = []
            for p in presencas:
                participante.append(p.participante)
            sorteado = participante
            sorteado = sorteado[SystemRandom().randint(1, len(sorteado)) - 1]
            return render_template(
                "gerenciar/sortear_usuario.html",
                usuario=current_user,
                form=form,
                participante=participante,
                sorteado=sorteado,
                sorteando=True,
                form_login=form_login,
            )
        else:
            return render_template(
                "gerenciar/sortear_usuario.html",
                usuario=current_user,
                form=form,
                vazio=True,
                sorteando=False,
                form_login=form_login,
            )
    else:
        abort(403)


@gerenciar.route("/alterar-camisetas", methods=["GET", "POST"])
@login_required
def alterar_camiseta():
    permissoes = current_user.getPermissoes()
    if "ALTERAR_CAMISETAS" in permissoes or current_user.is_admin():
        form_login = LoginForm(request.form)
        form = AlteraCamisetaForm(request.form)
        if form.validate_on_submit() and form.participante.data is not None:
            participante = db.session.query(Participante).filter_by(id=form.participante.data).first()
            camiseta = db.session.query(Camiseta).filter_by(id=form.camiseta.data).first()
            if camiseta.quantidade_restante > 0:
                antiga = (
                    db.session.query(Pagamento)
                    .filter_by(efetuado=True, cancelado=False, rejeitado=False, id_participante=participante.id)
                    .first()
                )
                camiseta_antiga = db.session.query(Camiseta).filter_by(id=antiga.id_camiseta).first()
                camiseta_antiga.quantidade_restante = camiseta_antiga.quantidade_restante + 1
                camiseta.quantidade_restante = camiseta.quantidade_restante - 1
                participante.id_camiseta = camiseta.id
                db.session.add(camiseta_antiga)

app/templates/gerenciar/add_pont.html
{% extends "participantes/sidebar.html" %}
{% import "wtf.html" as wtf %}

{% block sidebar_content %}
<div class="container">

    <div class="row justify-content-center pt-1">

        <div class="col-md-6">
            <h3 class="text-center">Cadastro de pontuação</h3>
            {% if sucesso %}
                <h5>Done!</h5>
            {% endif %}

            <form method="POST" action="{{ url_for('gerenciar.add_pontuacao') }}">
                {{ form.hidden_tag() }}
                {{ wtf.form_field(form.participante) }}
                {{ wtf.form_field(form.pontuacao) }}
                <button type="submit" class="btn btn-primary btn-block">Cadastrar</button>
             </form>
            <br>
        </div>
	</div>

</div>

{% endblock %}

app/templates/gerenciar/alterar_camisetas.html
{% extends "participantes/sidebar.html" %}
{% import "wtf.html" as wtf %}

{% block sidebar_content %}

<div class="container pt-3">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <h2 class="text-center pb-2">Alterar camisetas de usuários</h2>

            <form method="POST" action="{{url_for('gerenciar.alterar_camiseta')}}">
                {% if sucesso == 's': %}
                <div class="alert alert-success" role="alert">
                    Alteração efetuada com sucesso.
                </div>
                {% elif sucesso == 'n' %}
                <div class="alert alert-danger" role="alert">
                    Erro! Sem unidades de {{camiseta.tamanho}} disponíveis.
                </div>
                {% endif %}
                <h4 class="text-center">Obs: só funciona para participantes que compraram 1 único kit</h4>
                {{ form.hidden_tag() }}
                {{ wtf.form_field(form.participante) }}
                {{ wtf.form_field(form.camiseta) }}
                <div class="text-center">
                    <button type="submit" class="btn btn-primary w-50 mt-4">Alterar</button>
                </div>
                <br><br>
            </form>
        </div>
    </div>
</div>

{% endblock %}

app/templates/gerenciar/cadastro_participante_presencial.html
{% extends "participantes/sidebar.html" %}
{% import "wtf.html" as wtf %}

{% block sidebar_content %}

<style>

  .select2-selection__rendered {
    line-height: 31px !important;
  }

  .select2-container .select2-selection--single {
    height: 35px !important;
  }

  .select2-selection__arrow {
    height: 34px !important;
  }
</style>

<div class="container">

    <div class="row justify-content-center pt-1">
        <div class="col-md-8">
            <h3 class="text-center" style="margin-bottom: 30px">Cadastro presencial de participante</h3>
            <form method="POST" action="cadastro-presencial-participante">
                <div class="form-group">
                  {% if alerta is not sameas none %}
                    <div class="alert alert-info" role="alert">
                        {{ alerta }}
                    </div>
                  {% endif %}
                    {{ form.hidden_tag() }}
                    {{ wtf.form_field(form.usuario) }}
                    <label>Deseja confirmar manualmente o email do usuário?</label>
                    {{ wtf.form_field(form.confirmar_email) }}
                    <div class="text-center">
                        <button type="submit" class="btn btn-primary btn-block">Inscrever usuário</button>
                    </div>
                    <p class="text-center mt-2">
                        Com a ocorrência do fechamento das inscrições convencionais, o usuário cadastrado através dessa página <b>NÃO</b>
                        possuirá um crachá gerado a partir de nosso banco de dados. A <b>leitura de presenças em atividades</b> do participante
                        durante todo o evento deverá ser feita a partir do <b>QR CODE</b> que se encontra em nosso site, na <b>dashboard</b> do participante.
                    </p>
                </div>
            </form>
        </div>
    </div>
</div>
<script>

$("#usuario").select2({
  language: "pt-BR"
});

</script>

{% endblock %}

app/templates/gerenciar/cadastro_patrocinador.html
{% extends "participantes/sidebar.html" %}
{% import "wtf.html" as wtf %}
{% block sidebar_content %}

<div class="container">
    <div class="row justify-content-center pt-1">
        <div class="col-md-6">
            <h3 class="text-center">Cadastro de patrocinadores</h3>
            <form method="POST" action="{{ url_for('gerenciar.cadastro_patrocinador') }}"  enctype="multipart/form-data">
                {% if cadastrado %}
                <h3>Cadastrado!</h3>
                {% endif %}
                {{ form.hidden_tag() }}
                {{ wtf.form_field(form.nome_empresa) }}
                {{ wtf.form_field(form.id_cota) }}
                {{ wtf.form_field(form.link_website) }}
                {{ wtf.form_field(form.ativo_site) }}
                {{ wtf.form_field(form.logo) }}
                <button type="submit" class="btn btn-primary btn-block">Cadastrar</button>
            </form>
        </div>
    </div>
</div>

{% endblock %}

app/templates/gerenciar/controle_camisetas.html
{% extends "participantes/sidebar.html" %}
{% import "wtf.html" as wtf %}


{% block sidebar_content %}
<div class="container">

	<div class="row pt-1">
		<div class="col-md-12 text-center">
			<h2>Camisetas</h2>
		</div>
	</div>

	<div class="row justify-content-center">
		<!--

			COMENTADO PORQUE A PESQUISA NAO ESTAVA FUNCIONANDO

			<div class="col-md-6">
			<div class="input-group ">
				<input name="filtro" class="form-control" id="filtro" type="text" placeholder="Pesquisar modelo">
				<span class="input-group-btn">
					<button id="buscar" class="btn btn-primary">
						<span class="fas fa-search"></span>
					</button>
				</span>
			</div>
		</div>
	
	-->
		<div class="col-md-12">
			<a href="/admin/camiseta/" class="btn btn-primary float-right">Nova camiseta</a>
		</div>
	</div>
	<div id="list" class="row pt-1">
		<div class="table-responsive-md col-md-12">
			<table class="table table-striped">
				<thead>
					<tr>
						<th>ID</th>
						<th>Tamanho</th>
						<th>Quantidade disponível</th>
						<th>Quantidade pedida</th>
					</tr>
				</thead>
				<tbody>
					{% for camiseta in camisetas %}
					<tr>
						<td>{{camiseta.id}}</td>
						<td>{{camiseta.tamanho}}</td>
						<td>{{camiseta.quantidade_restante}}</td>
						<td>{{camiseta.quantidade}}</td>
					</tr>
					{% endfor %}
				</tbody>
			</table>
		</div>
	</div>
</div>

{% endblock %}

{% block scripts %}

{{ super() }}

<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"
	integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous">
	</script>

<script type="text/javascript">
	$("#buscar").click(function () {
		var nome = $("#filtro").val();
		$(location).attr('href', '/estoque-camisetas/' + nome);
	});
</script>

{% endblock %}

app/templates/gerenciar/crd_flags.html
{% extends "participantes/sidebar.html" %}
{% import "wtf.html" as wtf %}

{% block sidebar_content %}
<div class="container">

    <div class="row justify-content-center pt-1">

        <div class="col-md-6">
            <h3 class="text-center">Cadastro de novas flags</h3>
            {% if cadastrado %}
                <h5>A Flag foi cadastrada com sucesso</h5>
            {% endif %}
            {% if desativada %}
                <h5>A Flag foi desativada com sucesso</h5>
            {% endif %}

            <form method="POST" action="{{ url_for('gerenciar.cadastro_flags') }}">
                {{ form.hidden_tag() }}
                {{ wtf.form_field(form.flag) }}
                {{ wtf.form_field(form.pontos) }}
                <button type="submit" class="btn btn-primary btn-block">Cadastrar</button>
             </form>
            <br>
        </div>
	</div>

    <div id="list" class="row justify-content-center pt-4">
		<div class="table-responsive-md">
			<table class="table table-striped">
				<thead>
					<tr>
                        <th>Flag</th>
                        <th>Pontos</th>
                        <th>Ativa</th>
                        <th>Quantidade de utilizações</th>
                        <th>Ação</th>
					</tr>
				</thead>
				<tbody>
					{% for flag in flags %}
					<tr>
                        <td>{{flag.codigo}}</td>
                        <td>{{flag.pontos}}</td>
                        <td>{{flag.ativa}}</td>
                        <td>{{flag.quantidade_utilizada}}</td>
                        <td><a href="{{ url_for('gerenciar.cadastro_flags') }}/desativar/{{ flag.id }}">Desativar</a></td>
					</tr>
					{% endfor %}
				</tbody>
			</table>
		</div>
    </div>
</div>

{% endblock %}

app/templates/gerenciar/gerar_url_conteudo.html
{% extends "participantes/sidebar.html" %}
{% import "wtf.html" as wtf %}

{% block metas %}
{{ super() }}
<meta http-equiv="Cache-Control" content="no-cache, no-store, must-revalidate" />
<meta http-equiv="Pragma" content="no-cache" />
<meta http-equiv="Expires" content="0" />

{% endblock %}

{% block sidebar_content %}
<style>
  .clipboard {
    background-color: #cccccc;
  }

  .email-confirmado {
    display: inline;
    color: #006400;
  }

  .email-nao-confirmado {
    display: inline;
    color: #8B0000;
  }

  .select2-selection__rendered {
    line-height: 31px !important;
  }

  .select2-container .select2-selection--single {
    height: 35px !important;
  }

  .select2-selection__arrow {
    height: 34px !important;
  }
</style>
<div class="container pt-1">
  <h2 class="text-center pb-2">URL para formulários do Conteúdo</h2>

  <form method="POST" id="form" action="{{url_for('gerenciar.gerar_url_conteudo')}}">
    {{ form.hidden_tag() }}

    <div class="row justify-content-center">
      <div class="col-md-6 form-group">
        <label class="control-label" for="email2">Insira o email do(a) ministrante</label>
        <div class='input-group'>
          <input type="text" class="form-control pb-1" id="email2" placeholder="name@example.com">
          <div class="text-right input-group-btn">
            <button id="email_adder" type="button" class="btn btn-primary">Adicionar ministrante</button>
          </div>
        </div>
      </div>
      <div class="col-md-1"></div>
      <div class="col-md-3">
        {{ wtf.form_field(form.tipo_atividade) }}
      </div>
      <div class="col-md-2"></div>
    </div>

    <div class="row justify-content-center">
      <div class="col-md-6 pt-2 pb-2" id='email-containerL'></div>
      <div class="col-md-6 pt-2 pb-2" id='email-containerR'></div>
    </div>

    <div class="row justify-content-center pt-3">
      <div class="col-md-4">
        <button type="submit" class="btn btn-primary btn-block">Gerar Nova URL</button>
      </div>
    </div>


    <div class="row justify-content-center pt-4" style="overflow-x: scroll; width:100%;">
      <div class="col-md-12">
        <table class="table text-center">
          <thead>
            <tr>
              <th scope="col">Remover</th>
              <th scope="col">Editar</th>
              <th scope="col">Atividade</th>
              <th scope="col">Título</th>
              <th scope="col">Código da URL</th>
              <th scope="col">Emails</th>
            </tr>
          </thead>
          <tbody>
            {% for url in dict_urls %}
            <tr>
              <td scope="col"><button type='submit' class="btn btn-default" name='removido' value='{{ url.id }}'><i
                    class="fa fa-times"></i></button></td>
              <td scope="col">
                {% if url.titulo_atividade != '-' %}
                <button type='button' class="btn btn-default" onclick="editar('{{ url.url }}')">
                  <i class="fa fa-pencil-alt"></i>
                </button>
                {% endif %}</td>
              <td scope="col">{{ url.tipo }}</td>
              <td scope="col">{{ url.titulo_atividade }}</td>
              <td scope="col">

                <div class="dropdown">
                  <button class="btn dropdown-toggle" type="button" data-toggle="dropdown" aria-expanded="false">
                    <i class="fa fa-link" aria-hidden="true"></i>
                  </button>
                  <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                    <div class="dropdown-item">
                      <button type="button" class="btn"
                        data-clipboard-text="{{ url_root }}area-conteudo/cadastro-ministrante/{{url.codigo_url}}">
                        <i class="fa fa-clipboard mr-3" aria-hidden="true"></i>
                        Ministrante
                      </button>
                    </div>
                    <div class="dropdown-item">
                      <button type="button" class="btn"
                        data-clipboard-text="{{url.url}}"
                        aria-hidden=true>
                        <i class="fa fa-clipboard mr-3" aria-hidden="true"></i>
                        Atividade
                      </button>
                    </div>
                    <div class="dropdown-item">
                      <button type="button" class="btn"
                        data-clipboard-text="{{url.codigo_url}}">
                        <i class="fa fa-clipboard mr-3" aria-hidden="true"></i>
                        Código
                      </button>
                    </div>
                  </div>
                </div>

              </td>
              <td scope="col">
                {% for email in url.emails %}
                {% if not loop.last: %}
                {% if email.confirmado == True %}
                <div class='email-confirmado'>{{ email.email }}</div><br>
                {% else %}
                <div class='email-nao-confirmado'>{{ email.email }}</div><br>
                {% endif %}
                {% else: %}
                {% if email.confirmado == True %}
                <div class='email-confirmado'>{{ email.email }}</div>
                {% else %}
                <div class='email-nao-confirmado'>{{ email.email }}</div>
                {% endif %}
                {% endif %}
                {% endfor %}
              </td>
              {% endfor %}
            </tr>
          </tbody>
        </table>
      </div>
    </div>
  </form>
</div>
<script>
  if (window.history.replaceState) {
    window.history.replaceState(null, null, window.location.href);
  }

  email_count = 0;
  function validateEmail($email) {
    var emailReg = /^([\w-\.]+@([\w-]+\.)+[\w-]{2,4})?$/;
    return emailReg.test($email);
  }

  function remover(num) {
    $('#email2' + parseInt(num)).remove();
    email_count = email_count - 1;
  }
  function editar(codigo) {
    window.open(codigo, '_blank');
  }

  $('#email_adder').click(function () {
    valor = $('#email2').val()
    if (valor != '' && validateEmail(valor)) {
      email_count = email_count + 1;
      $('#email2').val('');

      if (email_count % 2 == 1) {
        $("#email-containerL").append("<div class='input-group pt-2 pb-2' id='email2" + email_count.toString() +
          "'><span class='input-group-btn'><button type='button' class='btn btn-default' onclick='remover(" +
          email_count.toString() + ")'><i class='fa fa-times' aria-hidden='true'></i></button></span><input type='text' class='form-control' name='emails[]' value='" + valor +
          "' readonly='readonly'></div>");
      } else {
        $("#email-containerR").append("<div class='input-group pt-2 pb-2' id='email2" + email_count.toString() + "'><input type='text' class='form-control' name='emails[]' value='" + valor +
          "' readonly='readonly'><span class='input-group-btn'><button class='btn btn-default' onclick='remover(" +
          email_count.toString() + ")'><i class='fa fa-times' aria-hidden='true'></i></button></span></div>");
      }

    }
    else {
      alert('Entre com um email válido')
    }
  })

  $("#tipo_atividade").select2({
    language: "pt-BR"
  });
</script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/2.0.4/clipboard.min.js"></script>
<script>
  var clipboard = new ClipboardJS('.btn');
  clipboard.on('success', function (e) {
    console.log(e);
  });
  clipboard.on('error', function (e) {
    console.log(e);
  });
</script>
{% endblock %}

app/templates/gerenciar/gerenciar.html
{% extends "participantes/sidebar.html" %}
{% import "wtf.html" as wtf %}

{% block sidebar_content %}
<div class="container">
    <div class="row justify-content-center pt-1">
        <div class="col-md-12 text-center">
            <h1>Área Administrativa - {{ usuario.primeiro_nome }}</h1>
        </div>
    </div>
    <div class="row pt-3">
        {% if usuario in permissoes['ADMIN'].usuarios or usuario in permissoes['CONTEUDO'].usuarios or usuario in permissoes['PATROCINIO'].usuarios %}
        <div class="col-md-6 p-3">
            <h4>Gerar URL para o cadastro de atividades e ministrantes</h4>
            <a href="{{url_for('.gerar_url_conteudo')}}" class="btn btn-primary">Gerar URL</a>
        </div>
        {% endif %}

        {% if usuario in permissoes['ADMIN'].usuarios %}
        <div class="col-md-6 p-3">
            <h4>Envio de emails</h4>
            <a href="#" class="btn btn-primary">Enviar email</a>
        </div>
        {% endif %}

        {% if usuario in permissoes['ADMIN'].usuarios or usuario in permissoes['NOTIFICACOES_APP'].usuarios %}
        <div class="col-md-6 p-3">
            <h4>Notificações</h4>
            <a href="#" class="btn btn-primary">Enviar notificações</a>
        </div>
        {% endif %}

        {% if usuario in permissoes['ADMIN'].usuarios or usuario in permissoes['VENDA_PRESENCIAL'].usuarios %}
        <div class="col-md-6 p-3">
            <h4>Venda de Kits</h4>
            <a href="{{url_for('.vender_kits')}}" class="btn btn-primary">Vender kit</a>
        </div>
        {% endif %}

        {% if usuario in permissoes['ADMIN'].usuarios or usuario in permissoes['GERENCIAR_COMPROVANTES'].usuarios %}
        <div class="col-md-6 p-3">
            <h4>Pagamentos</h4>
            <a href="{{url_for('.gerenciar_comprovantes')}}" class="btn btn-primary">Gerenciar comprovantes</a>
        </div>
        {% endif %}

        {% if usuario in permissoes['ADMIN'].usuarios or usuario in permissoes['ALTERAR_CAMISETAS'].usuarios %}
        <div class="col-md-6 p-3">
            <h4>Camisetas</h4>
            <a href="{{ url_for('.alterar_camiseta') }}" class="btn btn-primary">Alterar reservas de camisetas</a>
            <a href="{{ url_for('.estoque_camisetas') }}" class="btn btn-primary">Controle de camisetas</a>
        </div>
        {% endif %}

        {% if usuario in permissoes['ADMIN'].usuarios or usuario in permissoes['GERAR_CRACHAS'].usuarios %}
        <div class="col-md-6 p-3">
            <h4>Geração de crachás</h4>
            <a href="{{ url_for('views.constr') }}" class="btn btn-primary">Gerar crachás</a>
        </div>
        {% endif %}

        {% if usuario in permissoes['ADMIN'].usuarios or usuario in permissoes['GERAR_LISTAS'].usuarios %}
        <div class="col-md-6 p-3">
            <h4>Geração de listas</h4>
            <a href="{{url_for('.listas')}}" class="btn btn-primary">Gerar Listas</a>
        </div>
        {% endif %}

        {% if usuario in permissoes['ADMIN'].usuarios or usuario in permissoes['SORTEAR'].usuarios %}
        <div class="col-md-6 p-3">
            <h4>Sortear participante presente</h4>
            <a href="{{url_for('.sorteia_usuario')}}" class="btn btn-primary">Sortear participante</a>
        </div>
        {% endif %}

        {% if usuario in permissoes['ADMIN'].usuarios or usuario in permissoes['CONTEUDO'].usuarios %}
        <div class="col-md-6 p-3">
            <h4>Flags</h4>
            <a href="{{ url_for('gerenciar.cadastro_flags') }}" class="btn btn-primary">Gerenciar Flags</a>
        </div>
            <div class="col-md-6 p-3">
            <h4>Flags</h4>
            <a href="{{ url_for('gerenciar.add_pontuacao') }}" class="btn btn-primary">Flags - Adicionar pontuação p/ usuário</a>
        </div>

        {% endif %}

        {% if usuario in permissoes['ADMIN'].usuarios or usuario in permissoes['CREDENCIAMENTO'].usuarios or usuario in permissoes['ADMIN'].usuarios or usuario.is_admin() is sameas true %}
        <div class="col-md-6 p-3">
            <h4>Cadastro presencial de participante</h4>
            <a href="{{ url_for('gerenciar.cadastro_presencial_participante') }}" class="btn btn-primary">Inscrever usuários</a>
        </div>
        {% endif %}
    </div>
</div>
{% endblock %}