app/controllers/routes/participantes.py
import uuid

from os import path, makedirs
from bcrypt import gensalt
from flask import request, redirect, flash, Blueprint, current_app
from flask_login import login_required, login_user, fresh_login_required
from itsdangerous import URLSafeTimedSerializer, SignatureExpired
from passlib.hash import pbkdf2_sha256
from werkzeug.utils import secure_filename

from app.controllers.forms.forms import *
from app.controllers.functions.dictionaries import *
from app.controllers.functions.email import *
from app.controllers.functions.helpers import *
from app.models.models import *
from sqlalchemy.orm import aliased
from app.controllers.functions.paypal import *
from flask_limiter import Limiter
from flask_limiter.util import get_remote_address


limiter = Limiter(
    get_remote_address,
    app=current_app,
)

participantes = Blueprint(
    "participantes",
    __name__,
    static_folder="static",
    template_folder="templates",
    url_prefix="/participantes",
)


def email_verificado_required(func):
    def decorated_view(*args, **kwargs):
        if not current_user.email_verificado:
            return redirect(url_for("participantes.verificar_email"))
        return func(*args, **kwargs)

    decorated_view.__name__ = func.__name__
    return decorated_view


@participantes.route("/cadastro", methods=["POST", "GET"])
def cadastro():
    """
    Renderiza a página de cadastro do projeto
    """

    form_login = LoginForm(request.form)
    form = CadastroForm(request.form)
    form.curso.choices = get_opcoes_cursos()
    form.instituicao.choices = get_opcoes_instituicoes()
    form.cidade.choices = get_opcoes_cidades()
    if form.validate_on_submit():
        serializer = URLSafeTimedSerializer(current_app.config["SECRET_KEY"])
        email = form.email.data
        salt = gensalt().decode("utf-8")
        token = serializer.dumps(email, salt=salt)
        agora = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        hash = pbkdf2_sha256.encrypt(form.senha.data, rounds=10000, salt_size=15)
        usuario = Usuario(
            email=email,
            senha=hash,
            ultimo_login=agora,
            data_cadastro=agora,
            primeiro_nome=form.primeiro_nome.data,
            sobrenome=form.sobrenome.data,
            id_curso=verifica_outro_escolhido(
                form.curso, Curso(nome=form.outro_curso.data)
            ),
            id_instituicao=verifica_outro_escolhido(
                form.instituicao, Instituicao(nome=form.outra_instituicao.data)
            ),
            id_cidade=verifica_outro_escolhido(
                form.cidade, Cidade(nome=form.outra_cidade.data)
            ),
            data_nascimento=form.data_nasc.data,
            token_email=token,
            autenticado=True,
            salt=salt,
        )
        como_conheceu = ComoConheceu(
            usuario=usuario,
            opcao=form.como_conheceu.data,
            outro=form.outro_como_conheceu.data,
        )
        db.session.add(usuario)
        db.session.add(como_conheceu)
        db.session.flush()
        db.session.commit()
        enviar_email_confirmacao(usuario, token)
        login_user(usuario, remember=True)
        return redirect(url_for(".verificar_email"))

    return render_template(
        "participantes/cadastro.html", form=form, form_login=form_login
    )


@participantes.route("/verificar-email")
@login_required
def verificar_email():
    form_login = LoginForm(request.form)
    permissoes = current_user.getPermissoes()
    if "MINISTRANTE" in permissoes:
        ministrante = True
    else:
        ministrante = False
    if email_confirmado():
        msg = "Seu email foi verificado com sucesso!"
        status = True
    else:
        msg = "Confirme o email de verificação que te enviamos!"
        status = False
    return render_template(
        "participantes/confirma_email.html",
        resultado=msg,
        status=status,
        ministrante=ministrante,
        form_login=form_login,
    )


@login_required
@limiter.limit("40/year")
@limiter.limit("20/month")
@limiter.limit("20/day")
@limiter.limit("20/hour")
@limiter.limit("5/minute")
@participantes.route("/reenviar-email", methods=["POST", "GET"])
@login_required
def reenviar_email():
    if current_user.email_verificado is not True:
        form_login = LoginForm(request.form)
        form = BaseRecaptchaForm(request.form)
        usuario = current_user
        if form.validate_on_submit():
            serializer = URLSafeTimedSerializer(current_app.config["SECRET_KEY"])
            email = current_user.email
            salt = gensalt().decode("utf-8")
            token = serializer.dumps(email, salt=salt)
            usuario.token_email = token
            usuario.salt = salt
            db.session.add(usuario)
            db.session.commit()
            enviar_email_confirmacao(usuario, token)
            return render_template(
                "participantes/email_reenviado.html",
                form_login=form_login,
                usuario=usuario,
            )
        return render_template(
            "participantes/reenviar_email.html",
            form_login=form_login,
            usuario=usuario,
            form=form,
        )
    else:
        return redirect(url_for("participantes.verificar_email"))


@participantes.route("/cadastro-participante", methods=["POST", "GET"])
@login_required
def cadastro_participante():
    """
    try:
        id_evento = db.session.query(Evento).filter_by(edicao=EDICAO_ATUAL).first().id
        if current_user.email_verificado:
            participante = db.session.query(Participante).filter_by(id_usuario=current_user.id, id_evento=id_evento).first()
            if participante is None:
                form = ParticipanteForm(request.form)
                participante = db.session.query(Participante).filter_by(id_usuario=current_user.id, id_evento=id_evento).first()
                if form.validate_on_submit() and participante is None:
                    agora = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
                    participante = Participante(id_usuario=current_user.id, id_evento=id_evento, data_inscricao=agora, credenciado=False, opcao_coffee=0,
                                    uuid=str(uuid.uuid1()))
                    db.session.add(participante)
                    db.session.flush()
                    db.session.commit()
                    return redirect(url_for('.comprar_kit'))
                else:
                    return render_template('participantes/cadastro_participante.html', form=form, usuario=current_user)
            else:
                return redirect(url_for('.dashboard'))
        else:
            return redirect(url_for('.verificar_email'))
    except SQLAlchemyError:
        db.session.rollback()
    """
    return redirect(url_for(".dashboard"))


@participantes.route("/alterar-dados-usuario", methods=["POST", "GET"])
@login_required
def alterar_usuario():
    usuario = db.session.query(Usuario).filter_by(id=current_user.id).first()
    form = EdicaoUsuarioForm(request.form)
    if form.validate_on_submit() and request.method == "POST":
        usuario.primeiro_nome = form.primeiro_nome.data
        usuario.sobrenome = form.sobrenome.data
        usuario.id_curso = verifica_outro_escolhido(
            form.curso, Curso(nome=(form.outro_curso.data))
        )
        usuario.id_instituicao = verifica_outro_escolhido(
            form.instituicao, Instituicao(nome=form.outra_instituicao.data)
        )
        usuario.id_cidade = verifica_outro_escolhido(
            form.cidade, Cidade(nome=form.outra_cidade.data)
        )
        usuario.data_nascimento = form.data_nasc.data
        db.session.flush()
        db.session.commit()
        return redirect(url_for(".dashboard"))
    else:
        form.primeiro_nome.data = usuario.primeiro_nome
        form.sobrenome.data = usuario.sobrenome
        form.curso.data = usuario.id_curso
        form.instituicao.data = usuario.id_instituicao
        form.cidade.data = usuario.id_cidade
        form.data_nasc.data = usuario.data_nascimento
        return render_template(
            "participantes/alterar_usuario.html",
            usuario=current_user,
            form=form,
            participante=db.session.query(Participante)
            .filter_by(usuario=current_user)
            .first(),
        )


@participantes.route("/dashboard", methods=["POST", "GET"])
@login_required
@email_verificado_required
def dashboard():
    if email_confirmado():
        participante = (
            db.session.query(Participante).filter_by(usuario=current_user).first()
        )
        return render_template(
            "participantes/dashboard_usuario.html",
            title="Dashboard",
            usuario=current_user,
            participante=participante,
        )
    else:
        db.session.add(current_user)
        db.session.commit()
        return redirect(url_for(".verificar_email"))


@participantes.route("/wifi-visitante", methods=["POST", "GET"])
@login_required
@email_verificado_required
def cadastro_wifi():
    participante = (
        db.session.query(Participante).filter_by(usuario=current_user).first()
    )
    if participante:
        form = WifiForm(request.form)
        if form.validate_on_submit():
            data = {
                "cpf": form.cpf.data,
                "nome": form.nome.data,
                "email": form.email.data,
            }
            res = cadastrar_wifi_visitante(data)
            if res:
                flash("Usuário cadastrado com sucesso na rede WIFI-VISITANTE!")
                participante.wifi = True
                db.session.add(participante)
                db.session.commit()
                return redirect(url_for(".dashboard"))
            flash("Um ou mais campos não foram preenchidos corretamente.")
        return render_template(
            "participantes/wifi_visitante.html",

app/templates/participantes/alterar_senha.html
{% extends "base.html" %}
{% import "wtf.html" as wtf %}

{% block content %}

<div class="container">
    <div class="row justify-content-center pt-1">
        <div class="col-md-8">
            <h3 class="text-center">Alteração de senha</h3>
            <label class="control-label">Digite a nova senha abaixo</label>
            <form method="POST" action="{{ form.action }}">
                {{ form.hidden_tag() }}
		{% if not status_envio_email %}
		{{ wtf.form_field(form.senha_atual) }}
		{% endif %}
		{{ wtf.form_field(form.nova_senha) }}
                {{ wtf.form_field(form.confirmacao) }}
                <div class="text-center">
                    <button type="submit" class="btn btn-primary p-3">Confirmar Alteração</button>
                </div>
            </form>
        </div>
    </div>
</div>

{% endblock %}

app/templates/participantes/cadastro.html
{% extends "base.html" %}
{% import "wtf.html" as wtf %}

{% block styles %}

{{ super() }}

<link href="{{ url_for('static', filename='css/forms.css') }}" rel="stylesheet" type="text/css" />

<style>
  .border-cadastro {
    border: 1px solid var(--border-color);
    border-radius: 1rem;
    padding: 1rem 2rem 1rem 2rem;
    margin: 1rem;
  }

  #content {
    border-left: 1rem solid var(--primary-color);
    border-right: 1rem solid var(--secondary-color);
  }

  @media (max-width: 500px) {
    .border-cadastro {
      padding: 1rem;
    }

    #content {
      border-left: 0.5rem solid var(--primary-color);
      border-right: 0.5rem solid var(--secondary-color);
    }
  }
</style>

{% endblock %}


{% block content %}

<div class="container pb-2">

  <div class="col-md-12 text-center p-2">
    <h2>Cadastro de Usuário</h2>
  </div>

  <form method="POST" action="{{ url_for('participantes.cadastro') }}" novalidate>
    {{ form.hidden_tag() }}

    <div class="row justify-content-center">
      <div class="col-md-8 border-cadastro">
        <h4>Acesso</h4>
        <h6><small>Informe corretamente seu email, ele será utilizado para confirmação do cadastro e
            envio de certificados.</small></h6>
        {{ wtf.form_field(form.email) }}
        {{ wtf.form_field(form.senha) }}
        {{ wtf.form_field(form.confirmacao) }}
      </div>
    </div>

    <div class="row justify-content-center">
      <div class="col-md-8 border-cadastro">
        <h4>Usuário</h4>
        {{ wtf.form_field(form.primeiro_nome) }}
        {{ wtf.form_field(form.sobrenome) }}
        {{ wtf.form_field(form.data_nasc) }}
        {{ wtf.form_field(form.cidade) }}
        {{ wtf.form_field(form.outra_cidade) }}
      </div>
    </div>

    <div class="row justify-content-center">
      <div class="col-md-8 border-cadastro">
        <h4>Acadêmico</h4>
        {{ wtf.form_field(form.curso) }}
        {{ wtf.form_field(form.outro_curso) }}
        {{ wtf.form_field(form.instituicao) }}
        {{ wtf.form_field(form.outra_instituicao) }}
        {{ wtf.form_field(form.como_conheceu) }}
        {{ wtf.form_field(form.outro_como_conheceu) }}
      </div>
    </div>

    <div class="row justify-content-center mb-2">
      <div class="col-md-8 text-center">
        {{ wtf.form_field(form.recaptcha) }}
        <button type="submit" class="btn btn-primary text-white w-75 pb-1">Cadastrar</button>
      </div>
    </div>
  </form>
</div>
{% endblock %}

{% block scripts %}

{{ super() }}

<script src="{{ url_for('static', filename='jquery/jquery.maskedinput.min.js') }}"></script>


<script>
  $(document).ready(function ($) {
    $("#data_nasc").mask("99/99/9999");
    if ($("#curso :selected").text() !== "0") {
      $("label[for='outro_curso']").hide();
      $("#outro_curso").hide();
    }
    if ($("#instituicao :selected").text() !== "Outra") {
      $("label[for='outra_instituicao']").hide();
      $("#outra_instituicao").hide();
    }
    if ($("#cidade :selected").text() !== "Outra") {
      $("label[for='outra_cidade']").hide();
      $("#outra_cidade").hide();
    }
    if ($("#como_conheceu :selected").text() !== "Outro") {
      $("label[for='outro_como_conheceu']").hide();
      $("#outro_como_conheceu").hide();
    }
    $("#data_nasc").mask("99/99/9999");
    $("#curso").change(function () {
      if ($("#curso :selected").text() === "Outro") {
        $("label[for='outro_curso']").show();
        $("#outro_curso").show();
      } else {
        $("label[for='outro_curso']").hide();
        $("#outro_curso").hide();
      }
    });
    $("#instituicao").change(function () {
      if ($("#instituicao :selected").text() === "Outra") {
        $("label[for='outra_instituicao']").show();
        $("#outra_instituicao").show();
      } else {
        $("label[for='outra_instituicao']").hide();
        $("#outra_instituicao").hide();
      }
    });
    $("#cidade").change(function () {
      if ($("#cidade :selected").text() === "Outra") {
        $("label[for='outra_cidade']").show();
        $("#outra_cidade").show();
      } else {
        $("label[for='outra_cidade']").hide();
        $("#outra_cidade").hide();
      }
    });
    $("#como_conheceu").change(function () {
      if ($("#como_conheceu :selected").text() === "Outro") {
        $("label[for='outro_como_conheceu']").show();
        $("#outro_como_conheceu").show();
      } else {
        $("label[for='outro_como_conheceu']").hide();
        $("#outro_como_conheceu").hide();
      }
    });
  });

  document.addEventListener("DOMContentLoaded", function () {
    var elements = document.getElementsByTagName("INPUT");
    for (var i = 0; i < elements.length; i++) {
      elements[i].oninvalid = function (e) {
        e.target.setCustomValidity("");
        if (!e.target.validity.valid) {
          e.target.setCustomValidity("Preencha esse campo");
        }
      };
      elements[i].oninput = function (e) {
        e.target.setCustomValidity("");
      };
    }
  })
</script>

{% endblock %}

app/templates/participantes/comprar_kit.html
{% extends "participantes/sidebar.html" %}
{% import "wtf.html" as wtf %}

{% block sidebar_content %}

<style>
    :root {
        --card-color: #fff;
        --border-color: #ced2d6;
    }

    [data-theme=dark] {
        --card-color: #191e1f;
        --border-color: #646A70;
    }

    .modal-content {
        background-color: var(--card-color);
    }

    .modal-header {
        border-bottom: 1px solid var(--border-color) !important;
    }

    .modal-footer {
        border-top: 1px solid var(--border-color) !important;
    }

    .help-block {
        color: red;
    }

    @media(orientation: landscape) {
        #img_kit {
            max-width: 50vw;
        }
    }

    @media(orientation: portrait) {
        #img_kit {
            max-width: 90vw;
        }
    }

    .radio {
        display: block;
        float: left;
        padding-right: 1rem;
    }

    .form-group {
        margin: 14px 0 0 0;
    }

    #forma_pagamento {
        margin-top: 14px;
    }

    label[for=camiseta],
    label[for=restricao_coffee],
    label[for=cupom_desconto],
    label[for=comprovante],
    #forma_pagamento,
    .checkbox>label {
        font-weight: bold;
    }

    .titulo {
        font-size: 25px;
        font-weight: bold;
    }

    #info_paypal,
    #info_conta {
        padding-top: 0px;
    }
</style>

<div class="container pt-4 pb-4">

    <div class="col-md-12 text-center pb-1">
        <h2 id="pergunta"><i class="fa fa-lg fa-cart-plus"></i>
            Deseja comprar o kit da SECOMP UFSCar?<small>*</small></h2>
    </div>

    <div class="row justify-content-center pb-3 mt-4">
        <img id="img_kit" src="{{ url_for('static', filename='images/kit_secomp.jpeg') }}" />
    </div>

    <form method="POST" action="{{url_for('participantes.comprar_kit')}}" enctype="multipart/form-data">

        {{ form.hidden_tag() }}
        <div class="row justify-content-around no-gutters">
            <div class="col-md-8 mb-4">
                <div id="escolha_compra">
                    <div class="row justify-content-between no-gutters">
                        <div class="col-md-12">
                            <h6>*A compra pode ser efetuada a qualquer momento</h6>
                        </div>
                        <div class="col-4">
                            <div class="row">
                                {{ wtf.form_field(form.comprar) }}
                            </div>
                            <button type='button' id='continuar' class="btn btn-primary"
                                onclick='continuar2()'>Dashboard</button>
                        </div>

                        <div class="col-6">
                            <h4 class="text-right">
                                <b>Valor:</b> R$ {{ valor }}
                            </h4>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <a name="pagamento"></a>
        <div id='info_kit' class="mt-4">
            <div class="row justify-content-around noheader-gutters">
                <div class="col-md-4">
                    {{ wtf.form_field(form.camiseta) }}
                    <a href="#" class="m-0 p-0" data-toggle="modal" data-target="#modalCamisetas"
                        onclick="$('#modalCamisetas').appendTo('body')">Dúvidas com o tamanho?</a>
                    {{ wtf.form_field(form.restricao_coffee) }}
                    <p id="forma_pagamento">Escolha a forma de pagamento</p>
                    {{ wtf.form_field(form.forma_pagamento) }}<br>
                    <div class="pt-4">
                        {{ wtf.form_field(form.uso_cupom_desconto) }}
                    </div>
                    <div id="desconto">
                        {{ wtf.form_field(form.cupom_desconto) }}
                    </div>
                </div>

                <div class="col-md-4" id="info_conta">
                    <div class="titulo pb-4">Dados para transferência</div>
                    <p><b>Agência:</b> 1888-0
                        <br><b>Conta:</b> 35716-2
                        <br><b>CPNJ:</b> 30800496/0001-49
                        <br><b>Banco:</b> Banco do Brasil</p>
                    {{ wtf.form_field(form.comprovante) }}
                    <button type="submit" class="btn btn-primary mt-2">Confirmar Pagamento</button>
                </div>
                <div class="col-md-4" id="info_paypal">
                    <div class="titulo pb-4">Informações PayPal</div>
                    <div class="pb-3 text-justify">Após pressionar "confirmar pagamento", você será redirecionado ao PayPal para
                        finalizar e confirmar seu pagamento.
                        Caso você possua algum pagamento pendente, você será redirecionado novamente para o PayPay
                        para
                        finalizá-lo. Se quiser alterar as
                        informações do KIT você precisará <a href="{{ url_for('participantes.pagamentos') }}"> cancelar
                            seu
                            pagamento pendente</a></div>
                    <button type="submit" class="btn btn-primary">Confirmar Pagamento</button>
                </div>
            </div>
        </div>

        <div class="row justify-content-around no-gutters">
            <div class="col-md-4">
                <div id="recaptcha">
                    {{ wtf.form_field(form.recaptcha) }}
                </div>
            </div>
            <div class="col-md-4">
            </div>
        </div>
    </form>
</div>

<div class="modal fade" id="modalCamisetas" tabindex=header"-1" role="dialog" aria-labelledby="Tabela de tamanhos"
    aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered modal-lg" role="document">
        <div class="modal-content" style="width: auto; margin: auto;">
            <div class="modal-header">
                <h5 class="modal-title text-center">
                    <b>Relação de tamanhos de camiseta</b>
                </h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <img id="img_kit" src="{{ url_for('static', filename='images/tamanho_camisetas.jpg') }}" />
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Fechar</button>
            </div>
        </div>
    </div>
</div>

{% endblock %}

{% block scripts %}

{{ super() }}

<script>
    function continuar2() {
        $(location).attr('href', '/participantes/dashboard');
    }
</script>

<script>

    $(document).ready(function () {
        if ($('#comprar-0').is(':checked')) {
            $('#info_kit').show();
            $('#recaptcha').show();
            $('#continuar').hide();
            location.href = "#pagamento";
        }


        if ($('#comprar-1').is(':checked')) {
            $('#info_kit').hide();
            $('#continuar').show();
            $('#recaptcha').hide();
        }

        if ($('#forma_pagamento-0').is(':checked')) {
            $('#info_conta').show();
            $('#info_paypal').hide();
        }

        if ($('#forma_pagamento-1').is(':checked')) {
            $('#info_conta').hide();
            $('#info_paypal').show();
        }

        if ($('#uso_cupom_desconto').is(':checked')) {
            $('#desconto').show();
        }
        else {
            $('#desconto').hide();
        }
    });
    $('#info_kit').hide();
    $('#info_conta').hide();
    $('#desconto').hide();
    $('#comprar-0').change(function () {
        if ($('#comprar-0').is(':checked')) {
            location.href = "#pagamento";
            $('#info_kit').show();
            $('#recaptcha').show();
            $('#continuar').hide();
        }
    });

    $('#comprar-1').change(function () {
        if ($('#comprar-1').is(':checked')) {
            $('#info_kit').hide();
            $('#recaptcha').hide();
            $('#continuar').show();
        }
    });

    $('#forma_pagamento-0').change(function () {
        if ($('#forma_pagamento-0').is(':checked')) {
            $('#info_conta').show();
            $('#info_paypal').hide();
        }
    });
    $('#forma_pagamento-1').change(function () {
        if ($('#forma_pagamento-1').is(':checked')) {
            $('#info_conta').hide();
            $('#info_paypal').show();
        }
    });

    $('#uso_cupom_desconto').change(function () {
        if ($('#uso_cupom_desconto').is(':checked')) {
            $('#desconto').show();
        }
        else {
            $('#desconto').hide();
        }
    });

    $('#comprovante').prop('required', false);

</script>

{% endblock %}

app/templates/participantes/email_reenviado.html
{% extends "base.html" %}

{% block content %}
<div class="container pt-4 pb-4">
	<div class="row justify-content-center" style="min-height: 70vh;">
		<div class="col-md-8 text-center align-self-center">
			<i class="fa fa-4x fa-check-circle mb-3"></i>
			<h4>E-mail de confirmação reenviado com sucesso</h4>
		</div>
	</div>
</div>
{% endblock %}

app/templates/participantes/sidebar.html
{% extends "base.html" %}

{% block modal_login %}{% endblock %}

{% block styles %}

{{ super() }}
<link href="{{ url_for('static', filename='css/sidebar.css') }}" rel="stylesheet" type="text/css" />

{% endblock %}

{% block content %}

<div class="d-flex" id="wrapper">

    <div class="border-right" id="sidebar-wrapper">
        <div class="sidebar-heading">
            {{ usuario.primeiro_nome }}
        </div>
        <div class="list-group list-group-flush">
            <a href="{{ url_for('participantes.dashboard') }}" class="list-group-item list-group-item-action">Dashboard</a>

            <button style="outline: none;" class="list-group-item list-group-item-action dropdown-btn">Dados
                <i class="fa fa-caret-down"></i>
            </button>

            <div class="dropdown-container">

                <a href="{{ url_for('participantes.dados') }}" class="list-group-item list-group-item-action">Dados Pessoais</a>
                <a href="{{ url_for('participantes.alterar_usuario') }}" class="list-group-item list-group-item-action">Editar Dados Pessoais</a>
                
                {% if participante %}
                <a href="{{ url_for('participantes.dados_participante') }}" class="list-group-item list-group-item-action">Dados de Participante</a>
                {% endif %}

            </div>

            {% if participante %}

            <a href="{{ url_for('participantes.comprar_kit') }}" class="list-group-item list-group-item-action">Compra de Kit</a>
            <a href="{{ url_for('participantes.pagamentos') }}" class="list-group-item list-group-item-action">Pagamentos</a>

            <button style="outline: none;" class="list-group-item list-group-item-action dropdown-btn">Atividades
                <i class="fa fa-caret-down"></i>
            </button>

            <div class="dropdown-container">

                <a href="{{ url_for('participantes.inscricao_minicursos') }}"
                    class="list-group-item list-group-item-action">Minicursos</a>
                <a href="{{ url_for('participantes.presencas') }}" class="list-group-item list-group-item-action">Presenças</a>
            </div>
                <button style="outline: none;" class="list-group-item list-group-item-action dropdown-btn">COMPCases
                <i class="fa fa-caret-down"></i>
            </button>

            <div class="dropdown-container">
                <a href="{{ url_for('participantes.submeter_flag') }}" class="list-group-item list-group-item-action">Flags</a>
                <a href="{{ url_for('views.pontuacao_compcases') }}" class="list-group-item list-group-item-action">Ranking</a>

            </div>

            {% else %}
            <a href="{{ url_for('participantes.cadastro_participante') }}"
                class="list-group-item list-group-item-action">Inscrever-se</a>

            {% endif %}

            {% if "ADMIN" in current_user.getPermissoes() or
            "CONTEUDO" in current_user.getPermissoes() or
            "PATROCINIO" in current_user.getPermissoes() or
            "NOTIFICACOES_APP" in current_user.getPermissoes() or
            "VENDA_PRESENCIAL" in current_user.getPermissoes() or
            "APROVAR_COMPROVANTES" in current_user.getPermissoes() or
            "GERAR_CRACHAS" in current_user.getPermissoes() or
            "GERAR_LISTAS" in current_user.getPermissoes() or
            "SORTEAR" in current_user.getPermissoes() %}

            <a href="{{ url_for('gerenciar.index') }}"
                class="list-group-item list-group-item-action">Gerenciamento</a>

            {% endif %}

            {% if "ADMIN" in current_user.getPermissoes() %}

            <a href="/admin" class="list-group-item list-group-item-action">Administração</a>

            {% endif %}

            {% if participante %}
            <a href="{{ url_for('participantes.cadastro_wifi') }}" class="list-group-item list-group-item-action">WIFI-VISITANTE</a>
            {% endif %}

            <a href="{{url_for('views.logout')}}" class="list-group-item list-group-item-action">Logout</a>
        </div>
    </div>

    <a id="btn-open" class="circle" href="javascript:void(0);" onclick="openNav()">
        <i class="fas fa-angle-right fa-lg"></i>
    </a>
    <a id="btn-close" class="circle" href="javascript:void(0);" onclick="closeNav()">
        <i class="fa fa-times fa-sm"></i>
    </a>

    <div id="sidebar-content" class="container-fluid">
        {% block sidebar_content %}{% endblock %}
    </div>
</div>

{% endblock %}

{% block scripts %}

{{ super() }}

<script>
    function openNav() {
        $("#sidebar-wrapper").fadeIn(200);
        setTimeout(function () {
            document.getElementById("sidebar-wrapper").style.display = "inline-block";
            document.getElementById("btn-close").style.display = "inline-block";
        }, 200);
        document.getElementById("sidebar-wrapper").style.marginLeft = "0";
        document.getElementById("btn-open").style.display = "none";
        $('#wrapper').attr('style', 'min-height:' + $("#sidebar-wrapper").height() + "px" + ';other-styles');
    }
    function closeNav() {
        document.getElementById("sidebar-wrapper").style.marginLeft = "-15rem";
        document.getElementById("btn-close").style.display = "none";
        setTimeout(function () {
            document.getElementById("sidebar-wrapper").style.display = "none";
            document.getElementById("btn-open").style.display = "inline-block";
        }, 200);
        $(".dropdown-container").css("display", "none");
        if ($("#sidebar-wrapper").height() > $(window).height()) {
            $('#wrapper').attr('style', 'min-height:100vh;other-styles');
        }
    }
</script>

<script>
    var dropdown = document.getElementsByClassName("dropdown-btn");
    var i;

    for (i = 0; i < dropdown.length; i++) {
        dropdown[i].addEventListener("click", function () {
            this.classList.toggle("dropdown-btn-active");
            var dropdownContent = this.nextElementSibling;
            if (dropdownContent.style.display === "block") {
                dropdownContent.style.display = "none";
            } else {
                dropdownContent.style.display = "block";
            }
        });
    }

</script>

{% endblock %}

{% block footer %}{% endblock %}