app/controllers/routes/conteudo.py
from os import path, makedirs
import hashlib
from bcrypt import gensalt, hashpw
from flask import request, redirect, flash, Blueprint, current_app, abort
from flask_login import login_required, login_user
from itsdangerous import URLSafeTimedSerializer, SignatureExpired
from passlib.hash import pbkdf2_sha256
from app.controllers.forms.forms import *
from app.controllers.functions.email import *
from app.controllers.functions.helpers import *
from app.models.models import *
from flask_wtf import FlaskForm
from flask_limiter import Limiter
from flask_limiter.util import get_remote_address
from werkzeug.utils import secure_filename

limiter = Limiter(
    get_remote_address,
    app=current_app,
)


conteudo = Blueprint(
    "conteudo",
    __name__,
    static_folder="static",
    template_folder="templates",
    url_prefix="/area-conteudo",
)


@limiter.limit("20/day")
@conteudo.route("/cadastro-ministrante/<codigo>", methods=["POST", "GET"])
def cadastro_ministrante(codigo):
    form_login = LoginForm(request.form)
    r = valida_url_codigo(None, codigo)
    permitido, emails = r[0], r[2]
    if permitido == True:
        form = CadastroMinistranteForm()
        form.codigo_url = codigo
        if form.validate_on_submit() and form.email.data in emails:
            serializer = URLSafeTimedSerializer(current_app.config["SECRET_KEY"])
            email = form.email.data
            salt = gensalt().decode("utf-8")
            token = serializer.dumps(email, salt=salt)
            agora = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
            hash = pbkdf2_sha256.encrypt(form.senha.data, rounds=10000, salt_size=15)
            permissao_ministrante = (
                db.session.query(Permissao).filter_by(nome="MINISTRANTE").first()
            )

            usuario = db.session.query(Usuario).filter_by(email=form.email.data).first()
            ministrante = usuario.ministrante

            if permissao_ministrante is not None:
                usuario.permissoes_usuario.append(permissao_ministrante)

            usuario.email = form.email.data
            usuario.senha = hash
            usuario.ultimo_login = agora
            usuario.data_cadastro = agora
            usuario.primeiro_nome = form.primeiro_nome.data
            usuario.sobrenome = form.sobrenome.data
            usuario.data_nascimento = form.data_nascimento.data
            usuario.token_email = token
            usuario.autenticado = True
            usuario.salt = salt

            db.session.add(usuario)
            db.session.commit()

            if form.foto.data:
                foto = form.foto.data
                filename = secure_filename(foto.filename)
                filename = f"{usuario.id}_{usuario.primeiro_nome}_{usuario.sobrenome}_{filename}"
                upload_path = path.join(
                    current_app.config["UPLOAD_FOLDER"], "fotos_ministrantes"
                )
                if not path.exists(upload_path):
                    makedirs(upload_path)

            ministrante.id_usuario = usuario.id
            ministrante.telefone = form.telefone.data
            ministrante.profissao = form.profissao.data
            ministrante.empresa_universidade = form.empresa_universidade.data
            ministrante.biografia = form.biografia.data
            if form.foto.data:
                ministrante.foto = filename
            ministrante.tamanho_camiseta = form.tamanho_camiseta.data
            ministrante.facebook = form.facebook.data
            ministrante.twitter = form.twitter.data
            ministrante.linkedin = form.linkedin.data
            ministrante.github = form.github.data

            db.session.add(ministrante)
            db.session.commit()
            if form.foto.data:
                foto.save(path.join(upload_path, filename))
            enviar_email_confirmacao(usuario, token)
            login_user(usuario, remember=True)
            return redirect(url_for("participantes.verificar_email"))
        return render_template(
            "conteudo/cadastro_ministrante.html",
            form=form,
            codigo=codigo,
            form_login=form_login,
        )
    else:
        abort(404)


@limiter.limit("20/day")
@conteudo.route("/dados-hospedagem-transporte/", methods=["POST", "GET"])
@login_required
def dados_hospedagem_transporte():
    permissoes = current_user.getPermissoes()
    if (
        "MINISTRANTE" in permissoes
        or "CONTEUDO" in permissoes
        or current_user.is_admin()
    ):
        form_login = LoginForm(request.form)
        (
            atividade_confirmada,
            atividade,
            view_atividade,
        ) = confirmacao_atividade_ministrante(current_user)
        dados_hospedagem_transporte = (
            db.session.query(DadosHospedagemTransporte)
            .filter_by(
                id_evento=get_id_evento_atual(),
                id_ministrante=current_user.ministrante.id,
            )
            .first()
        )
        if dados_hospedagem_transporte is not None and atividade_confirmada == False:
            return redirect(
                url_for("conteudo." + view_atividade, codigo=atividade.url_codigo)
            )
        form = CadastroInformacoesLocomocaoEstadia(request.form)
        if form.validate_on_submit():
            dados_hospedagem_transporte = DadosHospedagemTransporte(
                id_evento=get_id_evento_atual(),
                cidade_origem=form.cidade_origem.data,
                data_chegada_origem=form.data_chegada_sanca.data,
                data_chegada_partida=form.data_partida_sanca.data,
                transporte_ida_volta=form.transporte_ida_volta.data,
                opcoes_transporte_ida_volta=str(form.opcoes_transporte_ida_volta.data),
                transporte_sanca=form.transporte_sanca.data,
                opcoes_transporte_sanca=str(form.opcoes_transporte_sanca.data),
                hospedagem=form.hospedagem.data,
                necessidades_hospedagem=form.necessidades_hospedagem.data,
                observacoes=form.observacoes.data,
            )
            current_user.ministrante.dados_hospedagem_transporte.append(
                dados_hospedagem_transporte
            )
            db.session.add(dados_hospedagem_transporte)
            db.session.add(current_user)
            db.session.commit()
            print(atividade.url_codigo)
            return redirect(
                url_for("conteudo." + view_atividade, codigo=atividade.url_codigo)
            )
        return render_template(
            "conteudo/dados_hospedagem_transporte.html",
            form=form,
            form_login=form_login,
        )
    abort(404)


@limiter.limit("20/day")
@conteudo.route("/cadastro-atividade/minicurso/<codigo>", methods=["POST", "GET"])
@login_required
def cadastro_minicurso(codigo):
    permissoes = current_user.getPermissoes()
    if (
        "MINISTRANTE" in permissoes
        or "CONTEUDO" in permissoes
        or current_user.is_admin()
    ):
        form_login = LoginForm()
        permitido, atividade, emails = valida_url_codigo(current_user, codigo)
        ministrante = current_user.ministrante
        if permitido == True:
            if ministrante is not None:
                r_atividade_ministrante = (
                    db.session.query(RelacaoAtividadeMinistrante)
                    .filter_by(id_ministrante=ministrante.id, id_atividade=atividade.id)
                    .first()
                )
            else:
                r_atividade_ministrante = None
            if (
                "CONTEUDO" in permissoes
                or r_atividade_ministrante.admin_atividade is not False
            ):
                form = CadastroInformacoesMinicurso()
                if form.validate_on_submit():
                    ae_filename = None
                    m_filename = None

                    if form.apresentacao_extra.data:
                        apresentacao_extra = form.apresentacao_extra.data
                        ae_filename = secure_filename(apresentacao_extra.filename)
                        ae_filename = f"{current_user.id}_{current_user.primeiro_nome}_{current_user.sobrenome}_{ae_filename}"
                        ae_path = path.join(
                            current_app.config["UPLOAD_FOLDER"],
                            "minicursos/apresentacoes_extra",
                        )
                        if not path.exists(ae_path):
                            makedirs(ae_path)

                    if form.material.data:
                        material = form.material.data
                        m_filename = secure_filename(material.filename)
                        m_filename = f"{current_user.id}_{current_user.primeiro_nome}_{current_user.sobrenome}_{m_filename}"
                        m_path = path.join(
                            current_app.config["UPLOAD_FOLDER"], "minicursos/materiais"
                        )
                        if not path.exists(m_path):
                            makedirs(m_path)

                    info_minicurso = InfoMinicurso(
                        pre_requisitos=form.pre_requisitos.data,
                        planejamento=form.planejamento.data,
                        apresentacao_extra=ae_filename,
                        material=m_filename,
                        requisitos_hardware=form.requisitos_hardware.data,
                        requisitos_ide=form.requisitos_ide.data,
                        requisitos_bibliotecas_pacotes=form.requisitos_bibliotecas_pacotes.data,
                        requisitos_dependencias=form.requisitos_dependencias.data,
                        requisitos_sistema=form.requisitos_sistema.data,
                        requisitos_observacoes=form.requisitos_observacoes.data,
                        requisitos_github=form.requisitos_github.data,
                        dicas_instalacao=form.dicas_instalacao.data,
                    )

app/templates/conteudo/cadastro_minicurso.html
{% extends "base.html" %}
{% import "wtf.html" as wtf %}

{% block content %}
<style>
  .tooltip1 {
    position: relative;
    display: inline-block;
  }

  .tooltip1 .tooltiptext1 {
    visibility: hidden;
    width:500px;
    background-color: black;
    color: #fff;
    text-align: justify;
    border-radius: 6px;
    padding: 5px 9px 5px 9px;

    /* Position the tooltip */
    position: absolute;
    z-index: 1;
  }
  @media (max-width:550px){
    .tooltip1 .tooltiptext1 {
      visibility: hidden;
      width:250px;
      background-color: black;
      color: #fff;
      text-align: justify;
      border-radius: 6px;
      padding: 5px 9px 5px 9px;

      /* Position the tooltip */
      position: absolute;
      z-index: 1;
    }
  }

  .tooltip1:hover .tooltiptext1 {
    visibility: visible;
  }

  .help-block {
    color: red;
  }
</style>

<div class="container pt-4 pb-4">
  <div class="row justify-content-center">
    <div class="col-md-7">
      {% if atividade.titulo is none: %}
        <h2 class="text-center">Cadastro de Minicurso</h2>
      {% else %}
        <h2 class="text-center">Editar Minicurso: {{ atividade.titulo }}</h2>
      {% endif %}

      <form method="POST" action="{{url_for('conteudo.cadastro_minicurso', codigo=codigo)}}"
            enctype="multipart/form-data">
        {{ form.csrf_token }}
        {{ wtf.form_field(form.titulo) }}
        {{ wtf.form_field(form.descricao) }}
        {{ wtf.form_field(form.pre_requisitos) }}
        {{ wtf.form_field(form.planejamento) }}
        {{ wtf.form_field(form.apresentacao_extra) }}
        {{ wtf.form_field(form.material) }}

        <h4 class="pt-2">Para que a organização possa auxiliar da melhor maneira possível,
          preparando os laboratórios e evitando eventuais problemas,
          pedimos que você nos informe abaixo todos os
          requisitos de hardware e software
          do minicurso.</h4>
        <h5 class="pb-3">Quanto mais detalhes, melhor para podermos preparar tudo! (:</h5>
        {{ wtf.form_field(form.requisitos_dependencias) }}
        {{ wtf.form_field(form.requisitos_bibliotecas_pacotes) }}
        {{ wtf.form_field(form.requisitos_ide) }}
        {{ wtf.form_field(form.requisitos_sistema) }}
        {{ wtf.form_field(form.requisitos_observacoes) }}
        {{ wtf.form_field(form.requisitos_github) }}
        {{ wtf.form_field(form.requisitos_hardware) }}
        {{ wtf.form_field(form.dicas_instalacao) }}
        {{ wtf.form_field(form.observacoes) }}
        <div>
            <p>Termo e Condições de Inscrição</p>
            <p>ATENÇÃO! Este termo refere-se aos direitos e deveres tanto do contato convidado, quanto por parte da SECOMP UFSCar; tornando a leitura deste fundamental! Quaisquer dúvidas devem ser questionadas ao membro que lhe forneceu acesso a este formulário.</p>
            <embed src="{{ url_for('views.protected', filename='juridic/termo_condicoes_inscricao.pdf') }}" type="application/pdf" width="100%" height="600px"></embed>
        </div>
        {{ wtf.form_field(form.confirmacao) }}

        <button type="submit" class="btn btn-primary btn-block">Cadastrar</button>
      </form>
    </div>
    <script>

      $("label[for='descricao']").prepend('<div class="tooltip1"><img src="{{url_for("static", filename="images/info-icon.svg")}}" width=16>&nbsp;<span class="tooltiptext1">Breve descrição do minicurso, a ser utilizada na divulgação.</span></div>');
      $("label[for='pre_requisitos']").prepend('<div class="tooltip1"><img src="{{url_for("static", filename="images/info-icon.svg")}}" width=16>&nbsp;<span class="tooltiptext1">Liste aqui quais são os pré-requisitos recomendados aos participantes que desejarem se inscrever no minicurso.</span></div>');
      $("label[for='planejamento']").prepend('<div class="tooltip1"><img src="{{url_for("static", filename="images/info-icon.svg")}}" width=16>&nbsp;<span class="tooltiptext1">Descrição (o mais detalhada possível) da estrutura do minicurso, ou seja, a distribuição em que os conteúdos serão aplicados, bem como o tempo reservado para cada um destes. Vale destacar a recomendação para que distribua-se ½ teórico e ½ prático. Informação apenas para organização interna, a qual não será utilizada para divulgação.</span></div>');
      $("label[for='apresentacao_extra']").prepend('<div class="tooltip1"><img src="{{url_for("static", filename="images/info-icon.svg")}}" width=16>&nbsp;<span class="tooltiptext1">Pequena apresentação (não obrigatória) a ser preparada e enviada previamente, a qual não necessite de alguém para apresentá-la. Será exibida aos participantes em caso de algum imprevisto, para evitar descontentamentos por parte do público. Caso não seja necessária, o ministrante pode optar por utilizá-la no minicurso ou enviar posteriormente aos participantes como um adendo.</span></div>');
      $("label[for='material']").prepend('<div class="tooltip1"><img src="{{url_for("static", filename="images/info-icon.svg")}}" width=16>&nbsp;<span class="tooltiptext1">Se possível, envie-nos com antecedência os materiais a serem utilizados no minicurso (slides, vídeos, etc.)</span></div>');
      $("label[for='observacoes']").prepend('<div class="tooltip1"><img src="{{url_for("static", filename="images/info-icon.svg")}}" width=16>&nbsp;<span class="tooltiptext1">Deixe aqui alguma observação ou informação que julgar necessária.</span></div>');
      $("label[for='requisitos_dependencias']").prepend('<div class="tooltip1"><img src="{{url_for("static", filename="images/info-icon.svg")}}" width=16>&nbsp;<span class="tooltiptext1">Especifique todos os programas e dependências que serão usados no minicurso. Para evitar problemas, especifique também as versões desses programas, caso tenha alguma preferência. Exemplo: git, docker, elixir v1.9.1, phoenix v1.4.9, etc...</span></div>');
      $("label[for='requisitos_bibliotecas_pacotes']").prepend('<div class="tooltip1"><img src="{{url_for("static", filename="images/info-icon.svg")}}" width=16>&nbsp;<span class="tooltiptext1">Especifique todas as bibliotecas e pacotes necessários. Para evitar problemas, especifique também as versões desses pacotes e/ou bibliotecas.<br>Exemplo: Pacotes python3: flask, flask_login, flask_migrate, flask_admin, etc...</span></div>');
      $("label[for='requisitos_ide']").prepend('<div class="tooltip1"><img src="{{url_for("static", filename="images/info-icon.svg")}}" width=16>&nbsp;<span class="tooltiptext1">Especifique alguma IDE ou editor de texto de sua preferência. Caso não tenha uma preferência digite: Nenhum.<br>Exemplo: Atom, Sublime, Visual Studio Code, PyCharm, CodeBlocks, etc...</span></div>');
      $("label[for='requisitos_sistema']").prepend('<div class="tooltip1"><img src="{{url_for("static", filename="images/info-icon.svg")}}" width=16>&nbsp;<span class="tooltiptext1">Se o minicurso necessita que os participantes utilizem algum sistema operacional específico informe neste campo. Caso contrário digite: Nenhum.<br>Exemplo: Ubuntu, Kali Linux, Windows 10, etc...</span></div>');
      $("label[for='requisitos_observacoes']").prepend('<div class="tooltip1"><img src="{{url_for("static", filename="images/info-icon.svg")}}" width=16>&nbsp;<span class="tooltiptext1">Digite aqui alguma observação a respeito desses requisitos que julgar relevante ou que possa nos auxiliar.</span></div>');
      $("label[for='requisitos_github']").prepend('<div class="tooltip1"><img src="{{url_for("static", filename="images/info-icon.svg")}}" width=16>&nbsp;<span class="tooltiptext1">No caso de existir um repositório remoto no github ou em outro site para códigos e projetos a serem desenvolvidos no decorrer do minicurso, digite aqui o link desse repositório.</span></div>');
      $("label[for='requisitos_hardware']").prepend('<div class="tooltip1"><img src="{{url_for("static", filename="images/info-icon.svg")}}" width=16>&nbsp;<span class="tooltiptext1">Especifique aqui no caso do minicurso envolver algum tipo de hardware específico</span></div>');
      $("label[for='dicas_instalacao']").prepend('<div class="tooltip1"><img src="{{url_for("static", filename="images/info-icon.svg")}}" width=16>&nbsp;<span class="tooltiptext1">Especifique aqui alguma dica ou informação que possa nos auxiliar na instalação desses softwares :)</span></div>');

      {% if atividade.titulo is not none %}
      $('#titulo').val('{{atividade.titulo}}');
      {% endif %}
      {% if atividade.descricao is not none %}
      $('#descricao').val('{{atividade.descricao}}');
      {% endif %}
      {% if atividade.info_minicurso.pre_requisitos is not none %}
      $('#pre_requisitos').val('{{atividade.info_minicurso.pre_requisitos}}');
      {% endif %}
      {% if atividade.info_minicurso.planejamento is not none %}
      $('#planejamento').val('{{atividade.info_minicurso.planejamento}}');
      {% endif %}
      {% if atividade.info_minicurso.apresentacao_extra is not none %}
      $('#apresentacao_extra').val('{{atividade.info_minicurso.apresentacao_extra}}');
      {% endif %}
      {% if atividade.info_minicurso.requisitos_ide is not none %}
      $('#requisitos_ide').val('{{atividade.info_minicurso.requisitos_ide}}');
      {% endif %}
      {% if atividade.info_minicurso.requisitos_bibliotecas_pacotes is not none %}
      $('#requisitos_bibliotecas_pacotes').val('{{atividade.info_minicurso.requisitos_bibliotecas_pacotes}}');
      {% endif %}
      {% if atividade.info_minicurso.requisitos_dependencias is not none %}
      $('#requisitos_dependencias').val('{{atividade.info_minicurso.requisitos_dependencias}}');
      {% endif %}
      {% if atividade.info_minicurso.requisitos_sistema is not none %}
      $('#requisitos_sistema').val('{{atividade.info_minicurso.requisitos_sistema}}');
      {% endif %}
      {% if atividade.info_minicurso.requisitos_observacoes is not none %}
      $('#requisitos_observacoes').val('{{atividade.info_minicurso.requisitos_observacoes}}');
      {% endif %}
      {% if atividade.info_minicurso.requisitos_github is not none %}
      $('#requisitos_github').val('{{atividade.info_minicurso.requisitos_github}}');
      {% endif %}
      {% if atividade.info_minicurso.requisitos_hardware is not none %}
      $('#requisitos_hardware').val('{{atividade.info_minicurso.requisitos_hardware}}');
      {% endif %}
      {% if atividade.info_minicurso.dicas_instalacao is not none %}
      $('#dicas_instalacao').val('{{atividade.info_minicurso.dicas_instalacao}}');
      {% endif %}
      {% if atividade.observacoes is not none %}
      $('#observacoes').val('{{atividade.observacoes}}');
      {% endif %}

    </script>
    {% endblock %}

app/templates/conteudo/cadastro_ministrante.html
{% extends "base.html" %}
{% import "wtf.html" as wtf %}

{% block content %}

<style>
  .tooltip1 {
    position: relative;
    display: inline-block;
  }

  .tooltip1 .tooltiptext1 {
    visibility: hidden;
    width:500px;
    background-color: black;
    color: #fff;
    text-align: justify;
    border-radius: 6px;
    padding: 5px 9px 5px 9px;

    /* Position the tooltip */
    position: absolute;
    z-index: 1;
  }
  @media (max-width:550px){
    .tooltip1 .tooltiptext1 {
      visibility: hidden;
      width:250px;
      background-color: black;
      color: #fff;
      text-align: justify;
      border-radius: 6px;
      padding: 5px 9px 5px 9px;

      /* Position the tooltip */
      position: absolute;
      z-index: 1;
    }
  }

  .tooltip1:hover .tooltiptext1 {
    visibility: visible;
  }

  .help-block {
    color: red;
  }
</style>

<div class="container pt-4 pb-4">
  <div class="row justify-content-center">
    <div class="col-md-7">
      <h3 class="text-center">Cadastro</h3>
      <form method="POST" action="{{url_for('conteudo.cadastro_ministrante', codigo=codigo)}}"
        enctype="multipart/form-data">
        {{ form.hidden_tag() }}
        {{ wtf.form_field(form.primeiro_nome) }}
        {{ wtf.form_field(form.sobrenome) }}
        {{ wtf.form_field(form.email) }}
        {{ wtf.form_field(form.senha) }}
        {{ wtf.form_field(form.confirmacao) }}
        {{ wtf.form_field(form.data_nascimento) }}
        {{ wtf.form_field(form.telefone) }}
        {{ wtf.form_field(form.profissao) }}
        {{ wtf.form_field(form.empresa_universidade) }}
        {{ wtf.form_field(form.biografia) }}
        {{ wtf.form_field(form.foto) }}
        {{ wtf.form_field(form.tamanho_camiseta) }}
        {{ wtf.form_field(form.facebook) }}
        {{ wtf.form_field(form.twitter) }}
        {{ wtf.form_field(form.linkedin) }}
        {{ wtf.form_field(form.github) }}
        {{ wtf.form_field(form.recaptcha) }}
        <p>ATENÇÃO! Ainda é necessário o preenchimento de informações essenciais para ocorrência da atividade e vinda ao evento! Confirme seu endereço de e-mail para ter acesso a página em que isto deve ser feito.</p>
        <button type="submit" class="btn btn-primary btn-block">Cadastrar</button>
      </form>
    </div>
  </div>
</div>

<script>
  $('#data_nascimento').mask('00/00/0000');
  $('#telefone').mask('(00)00000-0000');

  $("label[for='data_nascimento']").prepend('<div class="tooltip1"><img src="{{url_for("static", filename="images/info-icon.svg")}}" width=16>&nbsp;<span class="tooltiptext1">Formato dd/mm/aaaa.</span></div>');

</script>
{% endblock %}

app/templates/conteudo/cadastro_sucesso.html
{% extends "base.html" %}

{% block content %}
<div class="container pt-4 pb-4">
	<div class="row justify-content-center" style="min-height: 70vh;">
		<div class="col-md-8 text-center align-self-center">

			<i class="fa fa-4x fa-check-circle"></i>
			<h4>Cadastro finalizado com sucesso!</h4>

		</div>
	</div>
</div>
{% endblock %}

app/templates/conteudo/dados_hospedagem_transporte.html
{% extends "base.html" %}
{% import "wtf.html" as wtf %}

{% block content %}

<style>
  .tooltip1 {
    position: relative;
    display: inline-block;
  }

  .tooltip1 .tooltiptext1 {
    visibility: hidden;
    width:500px;
    background-color: black;
    color: #fff;
    text-align: justify;
    border-radius: 6px;
    padding: 5px 9px 5px 9px;

    /* Position the tooltip */
    position: absolute;
    z-index: 1;
  }
  @media (max-width:550px){
    .tooltip1 .tooltiptext1 {
      visibility: hidden;
      width:250px;
      background-color: black;
      color: #fff;
      text-align: justify;
      border-radius: 6px;
      padding: 5px 9px 5px 9px;

      /* Position the tooltip */
      position: absolute;
      z-index: 1;
    }
  }

  .tooltip1:hover .tooltiptext1 {
    visibility: visible;
  }

  .help-block {
    color: red;
  }
</style>

<div class="container pt-4 pb-4">
  <div class="row justify-content-center">
    <div class="col-md-7">
      <h2 class="text-center">Dados de Hospedagem e Transporte</h2>

      <form method="POST" action="{{url_for('conteudo.dados_hospedagem_transporte')}}">
        {{ form.hidden_tag() }}
        {{ wtf.form_field(form.cidade_origem) }}
        {{ wtf.form_field(form.data_chegada_sanca) }}
        {{ wtf.form_field(form.data_partida_sanca) }}
        {{ wtf.form_field(form.transporte_ida_volta) }}
        {{ wtf.form_field(form.opcoes_transporte_ida_volta) }}
        {{ wtf.form_field(form.transporte_sanca) }}
        {{ wtf.form_field(form.opcoes_transporte_sanca) }}
        {{ wtf.form_field(form.hospedagem) }}
        {{ wtf.form_field(form.necessidades_hospedagem) }}
        {{ wtf.form_field(form.observacoes) }}
        <button type="submit" class="btn btn-primary btn-block">Cadastrar</button>
      </form>
    </div>
  </div>
</div>

<script>
  $(document).ready(function ($) {
    $('#data_chegada_sanca').mask('00/00/0000');
    $('#data_partida_sanca').mask('00/00/0000');

    if (!(('#transporte_ida_volta').checked)) {
      $('label[for="opcoes_transporte_ida_volta"]').hide();
      $('#opcoes_transporte_ida_volta').hide();
    }

    $('#transporte_ida_volta').change(function () {
      if (this.checked) {
        $('label[for="opcoes_transporte_ida_volta"]').show();
        $('#opcoes_transporte_ida_volta').show();
      } else {
        $('label[for="opcoes_transporte_ida_volta"]').hide();
        $('#opcoes_transporte_ida_volta').hide();
      }
    });


    if (!(('#transporte_sanca').checked)) {
      $('label[for="opcoes_transporte_sanca"]').hide();
      $('#opcoes_transporte_sanca').hide();
    }

    $('#transporte_sanca').change(function () {
      if (this.checked) {
        $('label[for="opcoes_transporte_sanca"]').show();
        $('#opcoes_transporte_sanca').show();
      } else {
        $('label[for="opcoes_transporte_sanca"]').hide();
        $('#opcoes_transporte_sanca').hide();
      }
    });


    if (!(('#hospedagem').checked)) {
      $('label[for="necessidades_hospedagem"]').hide();
      $('#necessidades_hospedagem').hide();
    }

    $('#hospedagem').change(function () {
      if (this.checked) {
        $('label[for="necessidades_hospedagem"]').show();
        $('#necessidades_hospedagem').show();
      } else {
        $('label[for="necessidades_hospedagem"]').hide();
        $('#necessidades_hospedagem').hide();
      }
    });
  });

  $("label[for='data_chegada_sanca']").prepend('<div class="tooltip1"><img src="{{url_for("static", filename="images/info-icon.svg")}}" width=16>&nbsp;<span class="tooltiptext1">Formato dd/mm/aaaa.</span></div>');
  $("label[for='data_partida_sanca']").prepend('<div class="tooltip1"><img src="{{url_for("static", filename="images/info-icon.svg")}}" width=16>&nbsp;<span class="tooltiptext1">Formato dd/mm/aaaa.</span></div>');
</script>

{% endblock %}